import type { Character } from './types';

export const CHARACTERS: Character[] = [
  // Histoire
  { id: 'alexandre-le-grand', name: 'Alexandre le Grand', theme: 'histoire', tags: ['conquerant', 'antiquite', 'militaire', 'empire', 'stratege'] },
  { id: 'genghis-khan', name: 'Genghis Khan', theme: 'histoire', tags: ['conquerant', 'moyen-age', 'militaire', 'empire', 'stratege'] },
  { id: 'napoleon', name: 'Napoléon Bonaparte', theme: 'histoire', tags: ['conquerant', 'epoque-moderne', 'militaire', 'empire', 'stratege'] },
  { id: 'jules-cesar', name: 'Jules César', theme: 'histoire', tags: ['conquerant', 'antiquite', 'militaire', 'empire', 'politique'] },
  { id: 'cleopatre', name: 'Cléopâtre', theme: 'histoire', tags: ['antiquite', 'politique', 'egypte', 'diplomate', 'controverse'] },
  { id: 'leonard-de-vinci', name: 'Léonard de Vinci', theme: 'histoire', tags: ['renaissance', 'art', 'science', 'inventeur', 'visionnaire'] },
  { id: 'einstein', name: 'Albert Einstein', theme: 'histoire', tags: ['science', 'xxe-siecle', 'physique', 'visionnaire', 'pacifiste'] },
  { id: 'marie-curie', name: 'Marie Curie', theme: 'histoire', tags: ['science', 'xxe-siecle', 'physique', 'chimie', 'pionniere'] },
  { id: 'gandhi', name: 'Gandhi', theme: 'histoire', tags: ['xxe-siecle', 'politique', 'pacifiste', 'activiste', 'philosophe'] },
  { id: 'mlk', name: 'Martin Luther King', theme: 'histoire', tags: ['xxe-siecle', 'politique', 'pacifiste', 'activiste', 'orateur'] },
  { id: 'colomb', name: 'Christophe Colomb', theme: 'histoire', tags: ['explorateur', 'renaissance', 'navigateur', 'controverse', 'decouverte'] },
  { id: 'marco-polo', name: 'Marco Polo', theme: 'histoire', tags: ['explorateur', 'moyen-age', 'navigateur', 'commercant', 'decouverte'] },

  // Anime -- 20 series (9 with 40 characters, 11 with 10 characters)
  // One Piece
  { id: 'zoro', name: 'Roronoa Zoro', theme: 'anime', series: 'one-piece', tags: ['epeiste', 'pirate', 'shonen', 'determine', 'force-brute'] },
  { id: 'luffy', name: 'Monkey D. Luffy', theme: 'anime', series: 'one-piece', tags: ['pirate', 'shonen', 'hot-blooded', 'determine', 'protagoniste'] },
  { id: 'nami', name: 'Nami', theme: 'anime', series: 'one-piece', tags: ['pirate', 'shonen', 'stratege', 'navigateur', 'avide'] },
  { id: 'sanji', name: 'Sanji', theme: 'anime', series: 'one-piece', tags: ['pirate', 'shonen', 'combattant-corps-a-corps', 'charismatique', 'loyal'] },
  { id: 'nico-robin', name: 'Nico Robin', theme: 'anime', series: 'one-piece', tags: ['pirate', 'shonen', 'calme', 'mysterieux', 'genie'] },
  { id: 'chopper', name: 'Tony Tony Chopper', theme: 'anime', series: 'one-piece', tags: ['pirate', 'shonen', 'naif', 'attachant', 'loyal'] },
  { id: 'usopp', name: 'Usopp', theme: 'anime', series: 'one-piece', tags: ['pirate', 'shonen', 'peureux', 'comique', 'loyal'] },
  { id: 'franky', name: 'Franky', theme: 'anime', series: 'one-piece', tags: ['pirate', 'shonen', 'cyborg', 'comique', 'loyal'] },
  { id: 'brook', name: 'Brook', theme: 'anime', series: 'one-piece', tags: ['pirate', 'shonen', 'comique', 'loyal', 'epeiste'] },
  { id: 'trafalgar-law', name: 'Trafalgar Law', theme: 'anime', series: 'one-piece', tags: ['pirate', 'shonen', 'calme', 'stratege', 'rival'] },
  { id: 'jinbe', name: 'Jinbe', theme: 'anime', series: 'one-piece', tags: ['pirate', 'shonen', 'loyal', 'force-brute', 'calme'] },
  { id: 'portgas-d-ace', name: 'Portgas D. Ace', theme: 'anime', series: 'one-piece', tags: ['pirate', 'shonen', 'hot-blooded', 'charismatique', 'sacrifice'] },
  { id: 'sabo', name: 'Sabo', theme: 'anime', series: 'one-piece', tags: ['pirate', 'shonen', 'determine', 'loyal', 'revolutionnaire'] },
  { id: 'boa-hancock', name: 'Boa Hancock', theme: 'anime', series: 'one-piece', tags: ['pirate', 'shonen', 'orgueilleux', 'charismatique', 'seducteur'] },
  { id: 'shanks', name: 'Shanks', theme: 'anime', series: 'one-piece', tags: ['pirate', 'shonen', 'charismatique', 'calme', 'mentor'] },
  { id: 'dracule-mihawk', name: 'Dracule Mihawk', theme: 'anime', series: 'one-piece', tags: ['pirate', 'shonen', 'epeiste', 'calme', 'solitaire'] },
  { id: 'buggy', name: 'Buggy', theme: 'anime', series: 'one-piece', tags: ['pirate', 'shonen', 'comique', 'orgueilleux', 'excentrique'] },
  { id: 'crocodile', name: 'Crocodile', theme: 'anime', series: 'one-piece', tags: ['pirate', 'shonen', 'antagoniste', 'stratege', 'sombre'] },
  { id: 'doflamingo', name: 'Doflamingo', theme: 'anime', series: 'one-piece', tags: ['pirate', 'shonen', 'antagoniste', 'manipulateur', 'excentrique'] },
  { id: 'kaido', name: 'Kaido', theme: 'anime', series: 'one-piece', tags: ['pirate', 'shonen', 'antagoniste', 'force-brute', 'conquerant'] },
  { id: 'big-mom', name: 'Big Mom', theme: 'anime', series: 'one-piece', tags: ['pirate', 'shonen', 'antagoniste', 'force-brute', 'famille'] },
  { id: 'blackbeard', name: 'Blackbeard', theme: 'anime', series: 'one-piece', tags: ['pirate', 'shonen', 'antagoniste', 'ambitieux', 'manipulateur'] },
  { id: 'whitebeard', name: 'Whitebeard', theme: 'anime', series: 'one-piece', tags: ['pirate', 'shonen', 'mentor', 'force-brute', 'famille'] },
  { id: 'smoker', name: 'Smoker', theme: 'anime', series: 'one-piece', tags: ['marine', 'shonen', 'determine', 'discipline', 'loyal'] },
  { id: 'tashigi', name: 'Tashigi', theme: 'anime', series: 'one-piece', tags: ['marine', 'shonen', 'loyal', 'epeiste', 'determine'] },
  { id: 'koby', name: 'Koby', theme: 'anime', series: 'one-piece', tags: ['marine', 'shonen', 'naif', 'determine', 'loyal'] },
  { id: 'vivi', name: 'Nefertari Vivi', theme: 'anime', series: 'one-piece', tags: ['shonen', 'loyal', 'determine', 'diplomate', 'courageux'] },
  { id: 'perona', name: 'Perona', theme: 'anime', series: 'one-piece', tags: ['pirate', 'shonen', 'comique', 'excentrique', 'sombre'] },
  { id: 'bartolomeo', name: 'Bartolomeo', theme: 'anime', series: 'one-piece', tags: ['pirate', 'shonen', 'loyal', 'hot-blooded', 'comique'] },
  { id: 'rob-lucci', name: 'Rob Lucci', theme: 'anime', series: 'one-piece', tags: ['shonen', 'assassin', 'calme', 'force-brute', 'mysterieux'] },
  { id: 'bartholomew-kuma', name: 'Bartholomew Kuma', theme: 'anime', series: 'one-piece', tags: ['pirate', 'shonen', 'sacrifice', 'loyal', 'mysterieux'] },
  { id: 'kizaru', name: 'Kizaru', theme: 'anime', series: 'one-piece', tags: ['marine', 'shonen', 'blase', 'force-brute', 'excentrique'] },
  { id: 'aokiji', name: 'Aokiji', theme: 'anime', series: 'one-piece', tags: ['marine', 'shonen', 'calme', 'force-brute', 'blase'] },
  { id: 'akainu', name: 'Akainu', theme: 'anime', series: 'one-piece', tags: ['marine', 'shonen', 'antagoniste', 'force-brute', 'sombre'] },
  { id: 'yamato-op', name: 'Yamato', theme: 'anime', series: 'one-piece', tags: ['shonen', 'loyal', 'force-brute', 'idealiste', 'determine'] },
  { id: 'carrot', name: 'Carrot', theme: 'anime', series: 'one-piece', tags: ['pirate', 'shonen', 'comique', 'loyal', 'naif'] },
  { id: 'marco', name: 'Marco', theme: 'anime', series: 'one-piece', tags: ['pirate', 'shonen', 'loyal', 'calme', 'force-brute'] },
  { id: 'sengoku', name: 'Sengoku', theme: 'anime', series: 'one-piece', tags: ['marine', 'shonen', 'mentor', 'discipline', 'force-brute'] },
  { id: 'monkey-d-garp', name: 'Monkey D. Garp', theme: 'anime', series: 'one-piece', tags: ['marine', 'shonen', 'mentor', 'force-brute', 'comique'] },
  { id: 'silvers-rayleigh', name: 'Silvers Rayleigh', theme: 'anime', series: 'one-piece', tags: ['pirate', 'shonen', 'mentor', 'calme', 'genie'] },
  // Naruto
  { id: 'sasuke', name: 'Sasuke Uchiha', theme: 'anime', series: 'naruto', tags: ['ninja', 'shonen', 'vengeance', 'determine', 'rival'] },
  { id: 'naruto', name: 'Naruto Uzumaki', theme: 'anime', series: 'naruto', tags: ['ninja', 'shonen', 'determine', 'hot-blooded', 'protagoniste'] },
  { id: 'itachi', name: 'Itachi Uchiha', theme: 'anime', series: 'naruto', tags: ['ninja', 'shonen', 'stratege', 'sacrifice', 'calme'] },
  { id: 'sakura', name: 'Sakura Haruno', theme: 'anime', series: 'naruto', tags: ['ninja', 'shonen', 'determine', 'loyal', 'stratege'] },
  { id: 'kakashi', name: 'Kakashi Hatake', theme: 'anime', series: 'naruto', tags: ['ninja', 'shonen', 'calme', 'mentor', 'genie'] },
  { id: 'hinata', name: 'Hinata Hyuga', theme: 'anime', series: 'naruto', tags: ['ninja', 'shonen', 'timide', 'loyal', 'determine'] },
  { id: 'gaara', name: 'Gaara', theme: 'anime', series: 'naruto', tags: ['ninja', 'shonen', 'sombre', 'force-brute', 'redemption'] },
  { id: 'jiraiya', name: 'Jiraiya', theme: 'anime', series: 'naruto', tags: ['ninja', 'shonen', 'mentor', 'comique', 'sacrifice'] },
  { id: 'rock-lee', name: 'Rock Lee', theme: 'anime', series: 'naruto', tags: ['ninja', 'shonen', 'determine', 'hot-blooded', 'loyal'] },
  { id: 'shikamaru', name: 'Shikamaru Nara', theme: 'anime', series: 'naruto', tags: ['ninja', 'shonen', 'stratege', 'blase', 'genie'] },
  { id: 'tsunade', name: 'Tsunade', theme: 'anime', series: 'naruto', tags: ['ninja', 'shonen', 'mentor', 'genie', 'force-brute'] },
  { id: 'orochimaru', name: 'Orochimaru', theme: 'anime', series: 'naruto', tags: ['ninja', 'shonen', 'antagoniste', 'manipulateur', 'genie'] },
  { id: 'minato', name: 'Minato Namikaze', theme: 'anime', series: 'naruto', tags: ['ninja', 'shonen', 'genie', 'sacrifice', 'mentor'] },
  { id: 'obito', name: 'Obito Uchiha', theme: 'anime', series: 'naruto', tags: ['ninja', 'shonen', 'antagoniste', 'traumatise', 'manipulateur'] },
  { id: 'madara', name: 'Madara Uchiha', theme: 'anime', series: 'naruto', tags: ['ninja', 'shonen', 'antagoniste', 'force-brute', 'ambitieux'] },
  { id: 'nagato', name: 'Nagato (Pain)', theme: 'anime', series: 'naruto', tags: ['ninja', 'shonen', 'antagoniste', 'sombre', 'sacrifice'] },
  { id: 'konan', name: 'Konan', theme: 'anime', series: 'naruto', tags: ['ninja', 'shonen', 'calme', 'loyal', 'sacrifice'] },
  { id: 'neji', name: 'Neji Hyuga', theme: 'anime', series: 'naruto', tags: ['ninja', 'shonen', 'genie', 'determine', 'rival'] },
  { id: 'tenten', name: 'Tenten', theme: 'anime', series: 'naruto', tags: ['ninja', 'shonen', 'loyal', 'determine', 'discipline'] },
  { id: 'choji', name: 'Choji Akimichi', theme: 'anime', series: 'naruto', tags: ['ninja', 'shonen', 'loyal', 'comique', 'force-brute'] },
  { id: 'ino-yamanaka', name: 'Ino Yamanaka', theme: 'anime', series: 'naruto', tags: ['ninja', 'shonen', 'loyal', 'determine', 'stratege'] },
  { id: 'kiba', name: 'Kiba Inuzuka', theme: 'anime', series: 'naruto', tags: ['ninja', 'shonen', 'hot-blooded', 'loyal', 'impulsif'] },
  { id: 'shino', name: 'Shino Aburame', theme: 'anime', series: 'naruto', tags: ['ninja', 'shonen', 'calme', 'mysterieux', 'discipline'] },
  { id: 'temari', name: 'Temari', theme: 'anime', series: 'naruto', tags: ['ninja', 'shonen', 'stratege', 'determine', 'orgueilleux'] },
  { id: 'kankuro', name: 'Kankuro', theme: 'anime', series: 'naruto', tags: ['ninja', 'shonen', 'stratege', 'loyal', 'comique'] },
  { id: 'might-guy', name: 'Might Guy', theme: 'anime', series: 'naruto', tags: ['ninja', 'shonen', 'mentor', 'hot-blooded', 'discipline'] },
  { id: 'asuma', name: 'Asuma Sarutobi', theme: 'anime', series: 'naruto', tags: ['ninja', 'shonen', 'mentor', 'calme', 'sacrifice'] },
  { id: 'kurenai', name: 'Kurenai Yuhi', theme: 'anime', series: 'naruto', tags: ['ninja', 'shonen', 'calme', 'mentor', 'loyal'] },
  { id: 'iruka', name: 'Iruka Umino', theme: 'anime', series: 'naruto', tags: ['ninja', 'shonen', 'mentor', 'loyal', 'attachant'] },
  { id: 'hiruzen', name: 'Hiruzen Sarutobi', theme: 'anime', series: 'naruto', tags: ['ninja', 'shonen', 'mentor', 'sage', 'sacrifice'] },
  { id: 'jugo', name: 'Jugo', theme: 'anime', series: 'naruto', tags: ['ninja', 'shonen', 'force-brute', 'traumatise', 'loyal'] },
  { id: 'suigetsu', name: 'Suigetsu Hozuki', theme: 'anime', series: 'naruto', tags: ['ninja', 'shonen', 'sarcastique', 'impulsif', 'loyal'] },
  { id: 'karin', name: 'Karin', theme: 'anime', series: 'naruto', tags: ['ninja', 'shonen', 'loyal', 'determine', 'sarcastique'] },
  { id: 'deidara', name: 'Deidara', theme: 'anime', series: 'naruto', tags: ['ninja', 'shonen', 'antagoniste', 'excentrique', 'orgueilleux'] },
  { id: 'sasori', name: 'Sasori', theme: 'anime', series: 'naruto', tags: ['ninja', 'shonen', 'antagoniste', 'calme', 'genie'] },
  { id: 'kisame', name: 'Kisame Hoshigaki', theme: 'anime', series: 'naruto', tags: ['ninja', 'shonen', 'antagoniste', 'force-brute', 'loyal'] },
  { id: 'hidan', name: 'Hidan', theme: 'anime', series: 'naruto', tags: ['ninja', 'shonen', 'antagoniste', 'impulsif', 'immortel'] },
  { id: 'kakuzu', name: 'Kakuzu', theme: 'anime', series: 'naruto', tags: ['ninja', 'shonen', 'antagoniste', 'avide', 'calme'] },
  { id: 'haku', name: 'Haku', theme: 'anime', series: 'naruto', tags: ['ninja', 'shonen', 'loyal', 'sacrifice', 'calme'] },
  { id: 'zabuza', name: 'Zabuza Momochi', theme: 'anime', series: 'naruto', tags: ['ninja', 'shonen', 'force-brute', 'loyal', 'sombre'] },
  // Dragon Ball
  { id: 'goku', name: 'Goku', theme: 'anime', series: 'dragon-ball', tags: ['combattant-corps-a-corps', 'shonen', 'hot-blooded', 'force-brute', 'protagoniste'] },
  { id: 'vegeta', name: 'Vegeta', theme: 'anime', series: 'dragon-ball', tags: ['combattant-corps-a-corps', 'shonen', 'rival', 'force-brute', 'orgueilleux'] },
  { id: 'piccolo', name: 'Piccolo', theme: 'anime', series: 'dragon-ball', tags: ['combattant-corps-a-corps', 'shonen', 'mentor', 'calme', 'redemption'] },
  { id: 'gohan', name: 'Gohan', theme: 'anime', series: 'dragon-ball', tags: ['combattant-corps-a-corps', 'shonen', 'determine', 'loyal', 'genie'] },
  { id: 'bulma', name: 'Bulma', theme: 'anime', series: 'dragon-ball', tags: ['shonen', 'genie', 'stratege', 'sarcastique', 'independante'] },
  { id: 'krillin', name: 'Krillin', theme: 'anime', series: 'dragon-ball', tags: ['combattant-corps-a-corps', 'shonen', 'loyal', 'comique', 'courageux'] },
  { id: 'frieza', name: 'Frieza', theme: 'anime', series: 'dragon-ball', tags: ['shonen', 'antagoniste', 'sombre', 'genie', 'force-brute'] },
  { id: 'trunks', name: 'Trunks', theme: 'anime', series: 'dragon-ball', tags: ['combattant-corps-a-corps', 'shonen', 'determine', 'loyal', 'sacrifice'] },
  { id: 'master-roshi', name: 'Master Roshi', theme: 'anime', series: 'dragon-ball', tags: ['shonen', 'mentor', 'comique', 'genie', 'excentrique'] },
  { id: 'beerus', name: 'Beerus', theme: 'anime', series: 'dragon-ball', tags: ['shonen', 'force-brute', 'orgueilleux', 'mysterieux', 'impulsif'] },
  { id: 'cell', name: 'Cell', theme: 'anime', series: 'dragon-ball', tags: ['combattant-corps-a-corps', 'shonen', 'antagoniste', 'genie', 'force-brute'] },
  { id: 'majin-buu', name: 'Majin Buu', theme: 'anime', series: 'dragon-ball', tags: ['shonen', 'antagoniste', 'naif', 'force-brute', 'redemption'] },
  { id: 'android-18', name: 'C-18', theme: 'anime', series: 'dragon-ball', tags: ['combattant-corps-a-corps', 'shonen', 'sarcastique', 'independante', 'force-brute'] },
  { id: 'android-17', name: 'C-17', theme: 'anime', series: 'dragon-ball', tags: ['combattant-corps-a-corps', 'shonen', 'calme', 'force-brute', 'independante'] },
  { id: 'tien', name: 'Tenshinhan', theme: 'anime', series: 'dragon-ball', tags: ['combattant-corps-a-corps', 'shonen', 'loyal', 'discipline', 'determine'] },
  { id: 'yamcha', name: 'Yamcha', theme: 'anime', series: 'dragon-ball', tags: ['combattant-corps-a-corps', 'shonen', 'comique', 'loyal', 'blase'] },
  { id: 'chiaotzu', name: 'Chiaotzu', theme: 'anime', series: 'dragon-ball', tags: ['shonen', 'loyal', 'timide', 'attachant', 'sacrifice'] },
  { id: 'videl', name: 'Videl', theme: 'anime', series: 'dragon-ball', tags: ['combattant-corps-a-corps', 'shonen', 'determine', 'courageux', 'loyal'] },
  { id: 'goten', name: 'Goten', theme: 'anime', series: 'dragon-ball', tags: ['combattant-corps-a-corps', 'shonen', 'naif', 'comique', 'force-brute'] },
  { id: 'mr-satan', name: 'Mr. Satan', theme: 'anime', series: 'dragon-ball', tags: ['shonen', 'comique', 'orgueilleux', 'courageux', 'attachant'] },
  { id: 'whis', name: 'Whis', theme: 'anime', series: 'dragon-ball', tags: ['shonen', 'calme', 'genie', 'mysterieux', 'excentrique'] },
  { id: 'broly', name: 'Broly', theme: 'anime', series: 'dragon-ball', tags: ['combattant-corps-a-corps', 'shonen', 'force-brute', 'hot-blooded', 'traumatise'] },
  { id: 'bardock', name: 'Bardock', theme: 'anime', series: 'dragon-ball', tags: ['combattant-corps-a-corps', 'shonen', 'sacrifice', 'determine', 'force-brute'] },
  { id: 'king-kai', name: 'King Kai', theme: 'anime', series: 'dragon-ball', tags: ['shonen', 'mentor', 'comique', 'sage', 'genie'] },
  { id: 'dende', name: 'Dende', theme: 'anime', series: 'dragon-ball', tags: ['shonen', 'loyal', 'naif', 'mentor', 'calme'] },
  { id: 'mr-popo', name: 'Mr. Popo', theme: 'anime', series: 'dragon-ball', tags: ['shonen', 'mysterieux', 'loyal', 'calme', 'mentor'] },
  { id: 'korin', name: 'Korin', theme: 'anime', series: 'dragon-ball', tags: ['shonen', 'mentor', 'comique', 'sage', 'excentrique'] },
  { id: 'zamasu', name: 'Zamasu', theme: 'anime', series: 'dragon-ball', tags: ['shonen', 'antagoniste', 'idealiste', 'sombre', 'manipulateur'] },
  { id: 'goku-black', name: 'Goku Black', theme: 'anime', series: 'dragon-ball', tags: ['combattant-corps-a-corps', 'shonen', 'antagoniste', 'sombre', 'force-brute'] },
  { id: 'jiren', name: 'Jiren', theme: 'anime', series: 'dragon-ball', tags: ['combattant-corps-a-corps', 'shonen', 'force-brute', 'calme', 'discipline'] },
  { id: 'android-16', name: 'C-16', theme: 'anime', series: 'dragon-ball', tags: ['shonen', 'calme', 'pacifiste', 'force-brute', 'sacrifice'] },
  { id: 'dr-gero', name: 'Dr Gero', theme: 'anime', series: 'dragon-ball', tags: ['shonen', 'antagoniste', 'genie', 'sombre', 'manipulateur'] },
  { id: 'cooler', name: 'Cooler', theme: 'anime', series: 'dragon-ball', tags: ['shonen', 'antagoniste', 'orgueilleux', 'force-brute', 'rival'] },
  { id: 'nappa', name: 'Nappa', theme: 'anime', series: 'dragon-ball', tags: ['combattant-corps-a-corps', 'shonen', 'force-brute', 'hot-blooded', 'loyal'] },
  { id: 'raditz', name: 'Raditz', theme: 'anime', series: 'dragon-ball', tags: ['combattant-corps-a-corps', 'shonen', 'orgueilleux', 'force-brute', 'antagoniste'] },
  { id: 'king-piccolo', name: 'Piccolo Daimao', theme: 'anime', series: 'dragon-ball', tags: ['shonen', 'antagoniste', 'sombre', 'force-brute', 'mysterieux'] },
  { id: 'supreme-kai', name: 'Shin (Supreme Kai)', theme: 'anime', series: 'dragon-ball', tags: ['shonen', 'calme', 'sage', 'mentor', 'mysterieux'] },
  { id: 'pan', name: 'Pan', theme: 'anime', series: 'dragon-ball', tags: ['combattant-corps-a-corps', 'shonen', 'hot-blooded', 'determine', 'naif'] },
  { id: 'uub', name: 'Oub', theme: 'anime', series: 'dragon-ball', tags: ['combattant-corps-a-corps', 'shonen', 'naif', 'force-brute', 'determine'] },
  { id: 'vegito', name: 'Vegito', theme: 'anime', series: 'dragon-ball', tags: ['combattant-corps-a-corps', 'shonen', 'orgueilleux', 'force-brute', 'genie'] },
  // Death Note
  { id: 'light', name: 'Light Yagami', theme: 'anime', series: 'death-note', tags: ['stratege', 'seinen', 'antagoniste', 'manipulateur', 'genie'] },
  { id: 'l', name: 'L', theme: 'anime', series: 'death-note', tags: ['stratege', 'seinen', 'genie', 'detective', 'calme'] },
  { id: 'misa-amane', name: 'Misa Amane', theme: 'anime', series: 'death-note', tags: ['seinen', 'loyal', 'impulsif', 'attachant', 'manipulateur'] },
  { id: 'ryuk', name: 'Ryuk', theme: 'anime', series: 'death-note', tags: ['seinen', 'mysterieux', 'comique', 'blase', 'immortel'] },
  { id: 'near', name: 'Near', theme: 'anime', series: 'death-note', tags: ['stratege', 'seinen', 'genie', 'detective', 'calme'] },
  { id: 'mello', name: 'Mello', theme: 'anime', series: 'death-note', tags: ['stratege', 'seinen', 'impulsif', 'rival', 'determine'] },
  { id: 'soichiro-yagami', name: 'Soichiro Yagami', theme: 'anime', series: 'death-note', tags: ['seinen', 'loyal', 'detective', 'sacrifice', 'stratege'] },
  { id: 'teru-mikami', name: 'Teru Mikami', theme: 'anime', series: 'death-note', tags: ['seinen', 'sombre', 'loyal', 'manipulateur', 'genie'] },
  { id: 'rem', name: 'Rem', theme: 'anime', series: 'death-note', tags: ['seinen', 'mysterieux', 'sacrifice', 'loyal', 'immortel'] },
  { id: 'matsuda', name: 'Matsuda', theme: 'anime', series: 'death-note', tags: ['seinen', 'naif', 'comique', 'loyal', 'detective'] },
  // L'Attaque des Titans
  { id: 'levi', name: 'Levi Ackerman', theme: 'anime', series: 'attack-on-titan', tags: ['epeiste', 'seinen', 'force-brute', 'calme', 'capitaine'] },
  { id: 'erwin', name: 'Erwin Smith', theme: 'anime', series: 'attack-on-titan', tags: ['seinen', 'stratege', 'capitaine', 'sacrifice', 'visionnaire'] },
  { id: 'eren-yeager', name: 'Eren Yeager', theme: 'anime', series: 'attack-on-titan', tags: ['seinen', 'hot-blooded', 'transformation', 'vengeance', 'protagoniste'] },
  { id: 'mikasa', name: 'Mikasa Ackerman', theme: 'anime', series: 'attack-on-titan', tags: ['epeiste', 'seinen', 'loyal', 'determine', 'force-brute'] },
  { id: 'armin', name: 'Armin Arlert', theme: 'anime', series: 'attack-on-titan', tags: ['seinen', 'stratege', 'genie', 'loyal', 'sacrifice'] },
  { id: 'historia', name: 'Historia Reiss', theme: 'anime', series: 'attack-on-titan', tags: ['seinen', 'loyal', 'determine', 'sacrifice', 'redemption'] },
  { id: 'reiner', name: 'Reiner Braun', theme: 'anime', series: 'attack-on-titan', tags: ['seinen', 'transformation', 'sombre', 'sacrifice', 'traumatise'] },
  { id: 'annie', name: 'Annie Leonhart', theme: 'anime', series: 'attack-on-titan', tags: ['seinen', 'transformation', 'calme', 'mysterieux', 'combattant-corps-a-corps'] },
  { id: 'hange', name: 'Hange Zoe', theme: 'anime', series: 'attack-on-titan', tags: ['seinen', 'genie', 'excentrique', 'stratege', 'loyal'] },
  { id: 'zeke-yeager', name: 'Zeke Yeager', theme: 'anime', series: 'attack-on-titan', tags: ['seinen', 'stratege', 'transformation', 'manipulateur', 'antagoniste'] },
  { id: 'jean-kirstein', name: 'Jean Kirstein', theme: 'anime', series: 'attack-on-titan', tags: ['seinen', 'stratege', 'loyal', 'determine', 'sarcastique'] },
  { id: 'connie-springer', name: 'Connie Springer', theme: 'anime', series: 'attack-on-titan', tags: ['seinen', 'loyal', 'comique', 'naif', 'traumatise'] },
  { id: 'sasha-blouse', name: 'Sasha Blouse', theme: 'anime', series: 'attack-on-titan', tags: ['seinen', 'comique', 'loyal', 'attachant', 'determine'] },
  { id: 'ymir', name: 'Ymir', theme: 'anime', series: 'attack-on-titan', tags: ['seinen', 'transformation', 'sarcastique', 'loyal', 'mysterieux'] },
  { id: 'bertholdt', name: 'Bertholdt Hoover', theme: 'anime', series: 'attack-on-titan', tags: ['seinen', 'transformation', 'traumatise', 'sombre', 'sacrifice'] },
  { id: 'pieck', name: 'Pieck Finger', theme: 'anime', series: 'attack-on-titan', tags: ['seinen', 'transformation', 'calme', 'stratege', 'loyal'] },
  { id: 'grisha-yeager', name: 'Grisha Yeager', theme: 'anime', series: 'attack-on-titan', tags: ['seinen', 'mysterieux', 'sacrifice', 'sombre', 'determine'] },
  { id: 'carla-yeager', name: 'Carla Yeager', theme: 'anime', series: 'attack-on-titan', tags: ['seinen', 'loyal', 'sacrifice', 'famille', 'attachant'] },
  { id: 'kenny-ackerman', name: 'Kenny Ackerman', theme: 'anime', series: 'attack-on-titan', tags: ['seinen', 'mysterieux', 'force-brute', 'sombre', 'epeiste'] },
  { id: 'dot-pixis', name: 'Dot Pixis', theme: 'anime', series: 'attack-on-titan', tags: ['seinen', 'mentor', 'stratege', 'excentrique', 'calme'] },
  { id: 'nile-dok', name: 'Nile Dok', theme: 'anime', series: 'attack-on-titan', tags: ['seinen', 'loyal', 'stratege', 'discipline', 'calme'] },
  { id: 'ymir-fritz', name: 'Ymir Fritz', theme: 'anime', series: 'attack-on-titan', tags: ['seinen', 'sacrifice', 'mysterieux', 'transformation', 'sombre'] },
  { id: 'floch-forster', name: 'Floch Forster', theme: 'anime', series: 'attack-on-titan', tags: ['seinen', 'ambitieux', 'determine', 'antagoniste', 'hot-blooded'] },
  { id: 'gabi-braun', name: 'Gabi Braun', theme: 'anime', series: 'attack-on-titan', tags: ['seinen', 'determine', 'hot-blooded', 'traumatise', 'loyal'] },
  { id: 'falco-grice', name: 'Falco Grice', theme: 'anime', series: 'attack-on-titan', tags: ['seinen', 'loyal', 'sacrifice', 'determine', 'naif'] },
  { id: 'porco-galliard', name: 'Porco Galliard', theme: 'anime', series: 'attack-on-titan', tags: ['seinen', 'transformation', 'loyal', 'vengeance', 'determine'] },
  { id: 'willy-tybur', name: 'Willy Tybur', theme: 'anime', series: 'attack-on-titan', tags: ['seinen', 'manipulateur', 'charismatique', 'antagoniste', 'stratege'] },
  { id: 'theo-magath', name: 'Theo Magath', theme: 'anime', series: 'attack-on-titan', tags: ['seinen', 'stratege', 'discipline', 'calme', 'mentor'] },
  { id: 'moblit-berner', name: 'Moblit Berner', theme: 'anime', series: 'attack-on-titan', tags: ['seinen', 'loyal', 'attachant', 'sacrifice', 'calme'] },
  { id: 'rod-reiss', name: 'Rod Reiss', theme: 'anime', series: 'attack-on-titan', tags: ['seinen', 'antagoniste', 'manipulateur', 'sombre', 'famille'] },
  { id: 'keith-shadis', name: 'Keith Shadis', theme: 'anime', series: 'attack-on-titan', tags: ['seinen', 'mentor', 'discipline', 'force-brute', 'traumatise'] },
  { id: 'mina-carolina', name: 'Mina Carolina', theme: 'anime', series: 'attack-on-titan', tags: ['seinen', 'loyal', 'naif', 'sacrifice', 'attachant'] },
  { id: 'thomas-wagner', name: 'Thomas Wagner', theme: 'anime', series: 'attack-on-titan', tags: ['seinen', 'loyal', 'determine', 'sacrifice', 'naif'] },
  { id: 'marco-bott', name: 'Marco Bott', theme: 'anime', series: 'attack-on-titan', tags: ['seinen', 'loyal', 'idealiste', 'sacrifice', 'attachant'] },
  { id: 'petra-ral', name: 'Petra Ral', theme: 'anime', series: 'attack-on-titan', tags: ['seinen', 'loyal', 'calme', 'sacrifice', 'attachant'] },
  { id: 'oluo-bozado', name: 'Oluo Bozado', theme: 'anime', series: 'attack-on-titan', tags: ['seinen', 'loyal', 'comique', 'hot-blooded', 'sacrifice'] },
  { id: 'eld-jinn', name: 'Eld Jinn', theme: 'anime', series: 'attack-on-titan', tags: ['seinen', 'calme', 'loyal', 'stratege', 'sacrifice'] },
  { id: 'gunther-schultz', name: 'Gunther Schultz', theme: 'anime', series: 'attack-on-titan', tags: ['seinen', 'loyal', 'calme', 'discipline', 'sacrifice'] },
  { id: 'onyankopon', name: 'Onyankopon', theme: 'anime', series: 'attack-on-titan', tags: ['seinen', 'loyal', 'calme', 'attachant', 'determine'] },
  { id: 'ilse-langnar', name: 'Ilse Langnar', theme: 'anime', series: 'attack-on-titan', tags: ['seinen', 'mysterieux', 'determine', 'sacrifice', 'traumatise'] },
  // Fullmetal Alchemist
  { id: 'edward-elric', name: 'Edward Elric', theme: 'anime', series: 'fullmetal-alchemist', tags: ['alchimiste', 'shonen', 'determine', 'hot-blooded', 'protagoniste'] },
  { id: 'alphonse-elric', name: 'Alphonse Elric', theme: 'anime', series: 'fullmetal-alchemist', tags: ['alchimiste', 'shonen', 'loyal', 'sacrifice', 'protagoniste'] },
  { id: 'roy-mustang', name: 'Roy Mustang', theme: 'anime', series: 'fullmetal-alchemist', tags: ['alchimiste', 'shonen', 'stratege', 'charismatique', 'ambitieux'] },
  { id: 'riza-hawkeye', name: 'Riza Hawkeye', theme: 'anime', series: 'fullmetal-alchemist', tags: ['shonen', 'loyal', 'calme', 'determine', 'tireuse'] },
  { id: 'winry-rockbell', name: 'Winry Rockbell', theme: 'anime', series: 'fullmetal-alchemist', tags: ['shonen', 'genie', 'loyal', 'attachant', 'determine'] },
  { id: 'alex-armstrong', name: 'Alex Louis Armstrong', theme: 'anime', series: 'fullmetal-alchemist', tags: ['alchimiste', 'shonen', 'force-brute', 'comique', 'loyal'] },
  { id: 'scar', name: 'Scar', theme: 'anime', series: 'fullmetal-alchemist', tags: ['shonen', 'vengeance', 'sombre', 'force-brute', 'redemption'] },
  { id: 'king-bradley', name: 'King Bradley', theme: 'anime', series: 'fullmetal-alchemist', tags: ['shonen', 'antagoniste', 'epeiste', 'stratege', 'masque'] },
  { id: 'maes-hughes', name: 'Maes Hughes', theme: 'anime', series: 'fullmetal-alchemist', tags: ['shonen', 'loyal', 'comique', 'famille', 'sacrifice'] },
  { id: 'envy', name: 'Envy', theme: 'anime', series: 'fullmetal-alchemist', tags: ['shonen', 'antagoniste', 'transformation', 'manipulateur', 'sombre'] },
  // My Hero Academia
  { id: 'deku', name: 'Izuku Midoriya', theme: 'anime', series: 'my-hero-academia', tags: ['super-pouvoir', 'shonen', 'determine', 'protagoniste', 'courageux'] },
  { id: 'bakugo', name: 'Katsuki Bakugo', theme: 'anime', series: 'my-hero-academia', tags: ['super-pouvoir', 'shonen', 'hot-blooded', 'rival', 'orgueilleux'] },
  { id: 'all-might', name: 'All Might', theme: 'anime', series: 'my-hero-academia', tags: ['super-pouvoir', 'shonen', 'mentor', 'force-brute', 'sacrifice'] },
  { id: 'todoroki', name: 'Shoto Todoroki', theme: 'anime', series: 'my-hero-academia', tags: ['super-pouvoir', 'shonen', 'calme', 'traumatise', 'determine'] },
  { id: 'uraraka', name: 'Ochaco Uraraka', theme: 'anime', series: 'my-hero-academia', tags: ['super-pouvoir', 'shonen', 'loyal', 'determine', 'attachant'] },
  { id: 'iida', name: 'Tenya Iida', theme: 'anime', series: 'my-hero-academia', tags: ['super-pouvoir', 'shonen', 'loyal', 'stratege', 'discipline'] },
  { id: 'shigaraki', name: 'Tomura Shigaraki', theme: 'anime', series: 'my-hero-academia', tags: ['super-pouvoir', 'shonen', 'antagoniste', 'sombre', 'traumatise'] },
  { id: 'kirishima', name: 'Eijiro Kirishima', theme: 'anime', series: 'my-hero-academia', tags: ['super-pouvoir', 'shonen', 'loyal', 'courageux', 'hot-blooded'] },
  { id: 'kaminari', name: 'Denki Kaminari', theme: 'anime', series: 'my-hero-academia', tags: ['super-pouvoir', 'shonen', 'comique', 'loyal', 'naif'] },
  { id: 'yaoyorozu', name: 'Momo Yaoyorozu', theme: 'anime', series: 'my-hero-academia', tags: ['super-pouvoir', 'shonen', 'genie', 'stratege', 'calme'] },
  { id: 'tsuyu-asui', name: 'Tsuyu Asui', theme: 'anime', series: 'my-hero-academia', tags: ['super-pouvoir', 'shonen', 'calme', 'loyal', 'stratege'] },
  { id: 'mineta', name: 'Minoru Mineta', theme: 'anime', series: 'my-hero-academia', tags: ['super-pouvoir', 'shonen', 'comique', 'peureux', 'loyal'] },
  { id: 'tokoyami', name: 'Fumikage Tokoyami', theme: 'anime', series: 'my-hero-academia', tags: ['super-pouvoir', 'shonen', 'calme', 'sombre', 'discipline'] },
  { id: 'jiro', name: 'Kyoka Jiro', theme: 'anime', series: 'my-hero-academia', tags: ['super-pouvoir', 'shonen', 'sarcastique', 'loyal', 'determine'] },
  { id: 'shoji', name: 'Mezo Shoji', theme: 'anime', series: 'my-hero-academia', tags: ['super-pouvoir', 'shonen', 'calme', 'loyal', 'force-brute'] },
  { id: 'hagakure', name: 'Toru Hagakure', theme: 'anime', series: 'my-hero-academia', tags: ['super-pouvoir', 'shonen', 'comique', 'loyal', 'attachant'] },
  { id: 'aizawa', name: 'Shota Aizawa', theme: 'anime', series: 'my-hero-academia', tags: ['super-pouvoir', 'shonen', 'mentor', 'calme', 'discipline'] },
  { id: 'present-mic', name: 'Present Mic', theme: 'anime', series: 'my-hero-academia', tags: ['super-pouvoir', 'shonen', 'charismatique', 'comique', 'loyal'] },
  { id: 'midnight', name: 'Midnight', theme: 'anime', series: 'my-hero-academia', tags: ['super-pouvoir', 'shonen', 'charismatique', 'mentor', 'excentrique'] },
  { id: 'endeavor', name: 'Enji Todoroki (Endeavor)', theme: 'anime', series: 'my-hero-academia', tags: ['super-pouvoir', 'shonen', 'ambitieux', 'force-brute', 'redemption'] },
  { id: 'hawks', name: 'Hawks', theme: 'anime', series: 'my-hero-academia', tags: ['super-pouvoir', 'shonen', 'stratege', 'charismatique', 'mysterieux'] },
  { id: 'dabi', name: 'Dabi', theme: 'anime', series: 'my-hero-academia', tags: ['super-pouvoir', 'shonen', 'antagoniste', 'sombre', 'vengeance'] },
  { id: 'toga', name: 'Himiko Toga', theme: 'anime', series: 'my-hero-academia', tags: ['super-pouvoir', 'shonen', 'antagoniste', 'excentrique', 'sombre'] },
  { id: 'twice', name: 'Twice', theme: 'anime', series: 'my-hero-academia', tags: ['super-pouvoir', 'shonen', 'loyal', 'traumatise', 'attachant'] },
  { id: 'mirko', name: 'Rumi Usagiyama (Mirko)', theme: 'anime', series: 'my-hero-academia', tags: ['super-pouvoir', 'shonen', 'force-brute', 'orgueilleux', 'determine'] },
  { id: 'stain', name: 'Stain', theme: 'anime', series: 'my-hero-academia', tags: ['super-pouvoir', 'shonen', 'antagoniste', 'idealiste', 'sombre'] },
  { id: 'gran-torino', name: 'Gran Torino', theme: 'anime', series: 'my-hero-academia', tags: ['super-pouvoir', 'shonen', 'mentor', 'excentrique', 'force-brute'] },
  { id: 'mount-lady', name: 'Mount Lady', theme: 'anime', series: 'my-hero-academia', tags: ['super-pouvoir', 'shonen', 'ambitieux', 'charismatique', 'courageux'] },
  { id: 'mirio-togata', name: 'Mirio Togata', theme: 'anime', series: 'my-hero-academia', tags: ['super-pouvoir', 'shonen', 'courageux', 'loyal', 'determine'] },
  { id: 'nejire-hado', name: 'Nejire Hado', theme: 'anime', series: 'my-hero-academia', tags: ['super-pouvoir', 'shonen', 'excentrique', 'loyal', 'comique'] },
  { id: 'tamaki-amajiki', name: 'Tamaki Amajiki', theme: 'anime', series: 'my-hero-academia', tags: ['super-pouvoir', 'shonen', 'timide', 'loyal', 'force-brute'] },
  { id: 'overhaul', name: 'Kai Chisaki (Overhaul)', theme: 'anime', series: 'my-hero-academia', tags: ['super-pouvoir', 'shonen', 'antagoniste', 'calme', 'manipulateur'] },
  { id: 'inasa-yoarashi', name: 'Inasa Yoarashi', theme: 'anime', series: 'my-hero-academia', tags: ['super-pouvoir', 'shonen', 'hot-blooded', 'loyal', 'impulsif'] },
  { id: 'camie-utsushimi', name: 'Camie Utsushimi', theme: 'anime', series: 'my-hero-academia', tags: ['super-pouvoir', 'shonen', 'comique', 'excentrique', 'loyal'] },
  { id: 'spinner', name: 'Spinner', theme: 'anime', series: 'my-hero-academia', tags: ['super-pouvoir', 'shonen', 'loyal', 'idealiste', 'traumatise'] },
  { id: 'mr-compress', name: 'Mr. Compress', theme: 'anime', series: 'my-hero-academia', tags: ['super-pouvoir', 'shonen', 'excentrique', 'loyal', 'mysterieux'] },
  { id: 'gigantomachia', name: 'Gigantomachia', theme: 'anime', series: 'my-hero-academia', tags: ['super-pouvoir', 'shonen', 'loyal', 'force-brute', 'naif'] },
  { id: 'best-jeanist', name: 'Best Jeanist', theme: 'anime', series: 'my-hero-academia', tags: ['super-pouvoir', 'shonen', 'discipline', 'calme', 'mentor'] },
  { id: 'nezu', name: 'Nezu', theme: 'anime', series: 'my-hero-academia', tags: ['super-pouvoir', 'shonen', 'genie', 'mentor', 'calme'] },
  { id: 'eri', name: 'Eri', theme: 'anime', series: 'my-hero-academia', tags: ['super-pouvoir', 'shonen', 'timide', 'traumatise', 'attachant'] },
  // Demon Slayer
  { id: 'tanjiro', name: 'Tanjiro Kamado', theme: 'anime', series: 'demon-slayer', tags: ['epeiste', 'shonen', 'determine', 'protagoniste', 'loyal'] },
  { id: 'nezuko', name: 'Nezuko Kamado', theme: 'anime', series: 'demon-slayer', tags: ['transformation', 'shonen', 'loyal', 'sacrifice', 'protecteur'] },
  { id: 'zenitsu', name: 'Zenitsu Agatsuma', theme: 'anime', series: 'demon-slayer', tags: ['epeiste', 'shonen', 'peureux', 'comique', 'loyal'] },
  { id: 'inosuke', name: 'Inosuke Hashibira', theme: 'anime', series: 'demon-slayer', tags: ['epeiste', 'shonen', 'impulsif', 'force-brute', 'comique'] },
  { id: 'giyu', name: 'Giyu Tomioka', theme: 'anime', series: 'demon-slayer', tags: ['epeiste', 'shonen', 'calme', 'solitaire', 'loyal'] },
  { id: 'shinobu', name: 'Shinobu Kocho', theme: 'anime', series: 'demon-slayer', tags: ['epeiste', 'shonen', 'calme', 'vengeance', 'sarcastique'] },
  { id: 'rengoku', name: 'Kyojuro Rengoku', theme: 'anime', series: 'demon-slayer', tags: ['epeiste', 'shonen', 'hot-blooded', 'mentor', 'sacrifice'] },
  { id: 'muzan', name: 'Muzan Kibutsuji', theme: 'anime', series: 'demon-slayer', tags: ['shonen', 'antagoniste', 'transformation', 'sombre', 'immortel'] },
  { id: 'tengen', name: 'Tengen Uzui', theme: 'anime', series: 'demon-slayer', tags: ['epeiste', 'shonen', 'excentrique', 'force-brute', 'charismatique'] },
  { id: 'akaza', name: 'Akaza', theme: 'anime', series: 'demon-slayer', tags: ['shonen', 'antagoniste', 'force-brute', 'transformation', 'traumatise'] },
  { id: 'kanao-tsuyuri', name: 'Kanao Tsuyuri', theme: 'anime', series: 'demon-slayer', tags: ['epeiste', 'shonen', 'calme', 'loyal', 'traumatise'] },
  { id: 'mitsuri-kanroji', name: 'Mitsuri Kanroji', theme: 'anime', series: 'demon-slayer', tags: ['epeiste', 'shonen', 'attachant', 'force-brute', 'loyal'] },
  { id: 'obanai-iguro', name: 'Obanai Iguro', theme: 'anime', series: 'demon-slayer', tags: ['epeiste', 'shonen', 'calme', 'sombre', 'loyal'] },
  { id: 'gyomei-himejima', name: 'Gyomei Himejima', theme: 'anime', series: 'demon-slayer', tags: ['epeiste', 'shonen', 'force-brute', 'calme', 'sacrifice'] },
  { id: 'sanemi-shinazugawa', name: 'Sanemi Shinazugawa', theme: 'anime', series: 'demon-slayer', tags: ['epeiste', 'shonen', 'hot-blooded', 'vengeance', 'impulsif'] },
  { id: 'muichiro-tokito', name: 'Muichiro Tokito', theme: 'anime', series: 'demon-slayer', tags: ['epeiste', 'shonen', 'calme', 'genie', 'mysterieux'] },
  { id: 'kagaya-ubuyashiki', name: 'Kagaya Ubuyashiki', theme: 'anime', series: 'demon-slayer', tags: ['shonen', 'mentor', 'calme', 'charismatique', 'sacrifice'] },
  { id: 'amane-ubuyashiki', name: 'Amane Ubuyashiki', theme: 'anime', series: 'demon-slayer', tags: ['shonen', 'calme', 'loyal', 'mysterieux', 'sacrifice'] },
  { id: 'genya-shinazugawa', name: 'Genya Shinazugawa', theme: 'anime', series: 'demon-slayer', tags: ['shonen', 'determine', 'hot-blooded', 'traumatise', 'loyal'] },
  { id: 'kanae-kocho', name: 'Kanae Kocho', theme: 'anime', series: 'demon-slayer', tags: ['epeiste', 'shonen', 'calme', 'sacrifice', 'attachant'] },
  { id: 'sakonji-urokodaki', name: 'Sakonji Urokodaki', theme: 'anime', series: 'demon-slayer', tags: ['shonen', 'mentor', 'calme', 'discipline', 'loyal'] },
  { id: 'daki', name: 'Daki', theme: 'anime', series: 'demon-slayer', tags: ['shonen', 'antagoniste', 'transformation', 'sombre', 'orgueilleux'] },
  { id: 'gyutaro', name: 'Gyutaro', theme: 'anime', series: 'demon-slayer', tags: ['shonen', 'antagoniste', 'transformation', 'vengeance', 'sombre'] },
  { id: 'doma', name: 'Doma', theme: 'anime', series: 'demon-slayer', tags: ['shonen', 'antagoniste', 'manipulateur', 'charismatique', 'sombre'] },
  { id: 'kokushibo', name: 'Kokushibo', theme: 'anime', series: 'demon-slayer', tags: ['epeiste', 'shonen', 'antagoniste', 'force-brute', 'mysterieux'] },
  { id: 'nakime', name: 'Nakime', theme: 'anime', series: 'demon-slayer', tags: ['shonen', 'antagoniste', 'mysterieux', 'calme', 'manipulateur'] },
  { id: 'hantengu', name: 'Hantengu', theme: 'anime', series: 'demon-slayer', tags: ['shonen', 'antagoniste', 'peureux', 'transformation', 'sombre'] },
  { id: 'gyokko', name: 'Gyokko', theme: 'anime', series: 'demon-slayer', tags: ['shonen', 'antagoniste', 'excentrique', 'sombre', 'sarcastique'] },
  { id: 'enmu', name: 'Enmu', theme: 'anime', series: 'demon-slayer', tags: ['shonen', 'antagoniste', 'manipulateur', 'sombre', 'excentrique'] },
  { id: 'rui', name: 'Rui', theme: 'anime', series: 'demon-slayer', tags: ['shonen', 'antagoniste', 'transformation', 'traumatise', 'sombre'] },
  { id: 'kaigaku', name: 'Kaigaku', theme: 'anime', series: 'demon-slayer', tags: ['epeiste', 'shonen', 'antagoniste', 'orgueilleux', 'traumatise'] },
  { id: 'tamayo', name: 'Tamayo', theme: 'anime', series: 'demon-slayer', tags: ['shonen', 'calme', 'genie', 'loyal', 'mysterieux'] },
  { id: 'yushiro', name: 'Yushiro', theme: 'anime', series: 'demon-slayer', tags: ['shonen', 'loyal', 'calme', 'comique', 'sarcastique'] },
  { id: 'tanjuro-kamado', name: 'Tanjuro Kamado', theme: 'anime', series: 'demon-slayer', tags: ['shonen', 'mentor', 'calme', 'sacrifice', 'loyal'] },
  { id: 'kie-kamado', name: 'Kie Kamado', theme: 'anime', series: 'demon-slayer', tags: ['shonen', 'loyal', 'sacrifice', 'attachant', 'calme'] },
  { id: 'takeo-kamado', name: 'Takeo Kamado', theme: 'anime', series: 'demon-slayer', tags: ['shonen', 'loyal', 'naif', 'attachant', 'determine'] },
  { id: 'hanako-kamado', name: 'Hanako Kamado', theme: 'anime', series: 'demon-slayer', tags: ['shonen', 'loyal', 'attachant', 'naif', 'determine'] },
  { id: 'rokuro-kamado', name: 'Rokuta Kamado', theme: 'anime', series: 'demon-slayer', tags: ['shonen', 'loyal', 'naif', 'comique', 'attachant'] },
  { id: 'susamaru', name: 'Susamaru', theme: 'anime', series: 'demon-slayer', tags: ['shonen', 'antagoniste', 'impulsif', 'sombre', 'force-brute'] },
  { id: 'yahaba', name: 'Yahaba', theme: 'anime', series: 'demon-slayer', tags: ['shonen', 'antagoniste', 'loyal', 'sombre', 'impulsif'] },
  // Jujutsu Kaisen
  { id: 'yuji-itadori', name: 'Yuji Itadori', theme: 'anime', series: 'jujutsu-kaisen', tags: ['exorciste', 'shonen', 'determine', 'protagoniste', 'sacrifice'] },
  { id: 'gojo', name: 'Satoru Gojo', theme: 'anime', series: 'jujutsu-kaisen', tags: ['exorciste', 'shonen', 'genie', 'mentor', 'sarcastique'] },
  { id: 'megumi', name: 'Megumi Fushiguro', theme: 'anime', series: 'jujutsu-kaisen', tags: ['exorciste', 'shonen', 'calme', 'stratege', 'loyal'] },
  { id: 'nobara', name: 'Nobara Kugisaki', theme: 'anime', series: 'jujutsu-kaisen', tags: ['exorciste', 'shonen', 'determine', 'impulsif', 'sarcastique'] },
  { id: 'sukuna', name: 'Sukuna', theme: 'anime', series: 'jujutsu-kaisen', tags: ['exorciste', 'shonen', 'antagoniste', 'sombre', 'force-brute'] },
  { id: 'nanami', name: 'Nanami Kento', theme: 'anime', series: 'jujutsu-kaisen', tags: ['exorciste', 'shonen', 'calme', 'discipline', 'blase'] },
  { id: 'maki', name: 'Maki Zenin', theme: 'anime', series: 'jujutsu-kaisen', tags: ['exorciste', 'shonen', 'determine', 'force-brute', 'rival'] },
  { id: 'toge', name: 'Toge Inumaki', theme: 'anime', series: 'jujutsu-kaisen', tags: ['exorciste', 'shonen', 'calme', 'loyal', 'mysterieux'] },
  { id: 'yuta', name: 'Yuta Okkotsu', theme: 'anime', series: 'jujutsu-kaisen', tags: ['exorciste', 'shonen', 'genie', 'loyal', 'timide'] },
  { id: 'mahito', name: 'Mahito', theme: 'anime', series: 'jujutsu-kaisen', tags: ['exorciste', 'shonen', 'antagoniste', 'manipulateur', 'sombre'] },
  { id: 'panda', name: 'Panda', theme: 'anime', series: 'jujutsu-kaisen', tags: ['exorciste', 'shonen', 'comique', 'loyal', 'force-brute'] },
  { id: 'kasumi-miwa', name: 'Kasumi Miwa', theme: 'anime', series: 'jujutsu-kaisen', tags: ['exorciste', 'shonen', 'determine', 'loyal', 'naif'] },
  { id: 'aoi-todo', name: 'Aoi Todo', theme: 'anime', series: 'jujutsu-kaisen', tags: ['exorciste', 'shonen', 'force-brute', 'charismatique', 'excentrique'] },
  { id: 'mechamaru', name: 'Kokichi Muta (Mechamaru)', theme: 'anime', series: 'jujutsu-kaisen', tags: ['exorciste', 'shonen', 'stratege', 'loyal', 'mysterieux'] },
  { id: 'mai-zenin', name: 'Mai Zenin', theme: 'anime', series: 'jujutsu-kaisen', tags: ['exorciste', 'shonen', 'blase', 'sarcastique', 'determine'] },
  { id: 'noritoshi-kamo', name: 'Noritoshi Kamo', theme: 'anime', series: 'jujutsu-kaisen', tags: ['exorciste', 'shonen', 'discipline', 'calme', 'loyal'] },
  { id: 'mei-mei', name: 'Mei Mei', theme: 'anime', series: 'jujutsu-kaisen', tags: ['exorciste', 'shonen', 'avide', 'calme', 'sarcastique'] },
  { id: 'utahime-iori', name: 'Utahime Iori', theme: 'anime', series: 'jujutsu-kaisen', tags: ['exorciste', 'shonen', 'calme', 'loyal', 'stratege'] },
  { id: 'shoko-ieiri', name: 'Shoko Ieiri', theme: 'anime', series: 'jujutsu-kaisen', tags: ['exorciste', 'shonen', 'calme', 'sarcastique', 'loyal'] },
  { id: 'masamichi-yaga', name: 'Masamichi Yaga', theme: 'anime', series: 'jujutsu-kaisen', tags: ['exorciste', 'shonen', 'mentor', 'genie', 'calme'] },
  { id: 'jogo', name: 'Jogo', theme: 'anime', series: 'jujutsu-kaisen', tags: ['exorciste', 'shonen', 'antagoniste', 'hot-blooded', 'force-brute'] },
  { id: 'hanami', name: 'Hanami', theme: 'anime', series: 'jujutsu-kaisen', tags: ['exorciste', 'shonen', 'antagoniste', 'calme', 'sombre'] },
  { id: 'dagon', name: 'Dagon', theme: 'anime', series: 'jujutsu-kaisen', tags: ['exorciste', 'shonen', 'antagoniste', 'force-brute', 'orgueilleux'] },
  { id: 'choso', name: 'Choso', theme: 'anime', series: 'jujutsu-kaisen', tags: ['exorciste', 'shonen', 'loyal', 'calme', 'sacrifice'] },
  { id: 'yuki-tsukumo', name: 'Yuki Tsukumo', theme: 'anime', series: 'jujutsu-kaisen', tags: ['exorciste', 'shonen', 'force-brute', 'charismatique', 'independante'] },
  { id: 'kenjaku', name: 'Kenjaku', theme: 'anime', series: 'jujutsu-kaisen', tags: ['exorciste', 'shonen', 'antagoniste', 'manipulateur', 'genie'] },
  { id: 'geto-suguru', name: 'Suguru Geto', theme: 'anime', series: 'jujutsu-kaisen', tags: ['exorciste', 'shonen', 'antagoniste', 'charismatique', 'sombre'] },
  { id: 'yorozu', name: 'Yorozu', theme: 'anime', series: 'jujutsu-kaisen', tags: ['exorciste', 'shonen', 'antagoniste', 'genie', 'excentrique'] },
  { id: 'uraume', name: 'Uraume', theme: 'anime', series: 'jujutsu-kaisen', tags: ['exorciste', 'shonen', 'loyal', 'calme', 'mysterieux'] },
  { id: 'naoya-zenin', name: 'Naoya Zenin', theme: 'anime', series: 'jujutsu-kaisen', tags: ['exorciste', 'shonen', 'antagoniste', 'orgueilleux', 'sombre'] },
  { id: 'junpei-yoshino', name: 'Junpei Yoshino', theme: 'anime', series: 'jujutsu-kaisen', tags: ['exorciste', 'shonen', 'traumatise', 'sombre', 'determine'] },
  { id: 'hajime-kashimo', name: 'Hajime Kashimo', theme: 'anime', series: 'jujutsu-kaisen', tags: ['exorciste', 'shonen', 'hot-blooded', 'force-brute', 'excentrique'] },
  { id: 'takaba-fumihiko', name: 'Fumihiko Takaba', theme: 'anime', series: 'jujutsu-kaisen', tags: ['exorciste', 'shonen', 'comique', 'excentrique', 'impulsif'] },
  { id: 'kusakabe-atsuya', name: 'Atsuya Kusakabe', theme: 'anime', series: 'jujutsu-kaisen', tags: ['exorciste', 'shonen', 'loyal', 'calme', 'discipline'] },
  { id: 'ijichi-kiyotaka', name: 'Kiyotaka Ijichi', theme: 'anime', series: 'jujutsu-kaisen', tags: ['exorciste', 'shonen', 'peureux', 'loyal', 'comique'] },
  { id: 'rika-orimoto', name: 'Rika Orimoto', theme: 'anime', series: 'jujutsu-kaisen', tags: ['exorciste', 'shonen', 'mysterieux', 'sombre', 'loyal'] },
  { id: 'haruta-shigemo', name: 'Haruta Shigemo', theme: 'anime', series: 'jujutsu-kaisen', tags: ['exorciste', 'shonen', 'antagoniste', 'sarcastique', 'excentrique'] },
  { id: 'toji-fushiguro', name: 'Toji Fushiguro', theme: 'anime', series: 'jujutsu-kaisen', tags: ['exorciste', 'shonen', 'blase', 'calme', 'force-brute'] },
  { id: 'tsumiki-fushiguro', name: 'Tsumiki Fushiguro', theme: 'anime', series: 'jujutsu-kaisen', tags: ['shonen', 'loyal', 'attachant', 'sacrifice', 'calme'] },
  { id: 'hiromi-higuruma', name: 'Hiromi Higuruma', theme: 'anime', series: 'jujutsu-kaisen', tags: ['exorciste', 'shonen', 'stratege', 'discipline', 'determine'] },
  // Bleach
  { id: 'ichigo', name: 'Ichigo Kurosaki', theme: 'anime', series: 'bleach', tags: ['epeiste', 'shonen', 'hot-blooded', 'protagoniste', 'determine'] },
  { id: 'rukia', name: 'Rukia Kuchiki', theme: 'anime', series: 'bleach', tags: ['epeiste', 'shonen', 'calme', 'mentor', 'loyal'] },
  { id: 'orihime', name: 'Orihime Inoue', theme: 'anime', series: 'bleach', tags: ['shonen', 'loyal', 'attachant', 'naif', 'super-pouvoir'] },
  { id: 'uryu', name: 'Uryu Ishida', theme: 'anime', series: 'bleach', tags: ['shonen', 'orgueilleux', 'stratege', 'rival', 'discipline'] },
  { id: 'renji', name: 'Renji Abarai', theme: 'anime', series: 'bleach', tags: ['epeiste', 'shonen', 'loyal', 'hot-blooded', 'determine'] },
  { id: 'urahara', name: 'Kisuke Urahara', theme: 'anime', series: 'bleach', tags: ['shonen', 'genie', 'mysterieux', 'sarcastique', 'mentor'] },
  { id: 'byakuya', name: 'Byakuya Kuchiki', theme: 'anime', series: 'bleach', tags: ['epeiste', 'shonen', 'calme', 'orgueilleux', 'discipline'] },
  { id: 'toshiro', name: 'Toshiro Hitsugaya', theme: 'anime', series: 'bleach', tags: ['epeiste', 'shonen', 'calme', 'genie', 'determine'] },
  { id: 'grimmjow', name: 'Grimmjow Jaegerjaquez', theme: 'anime', series: 'bleach', tags: ['shonen', 'antagoniste', 'hot-blooded', 'force-brute', 'orgueilleux'] },
  { id: 'aizen', name: 'Sosuke Aizen', theme: 'anime', series: 'bleach', tags: ['shonen', 'antagoniste', 'manipulateur', 'genie', 'calme'] },
  { id: 'yoruichi', name: 'Yoruichi Shihoin', theme: 'anime', series: 'bleach', tags: ['epeiste', 'shonen', 'calme', 'mysterieux', 'genie'] },
  { id: 'kenpachi', name: 'Kenpachi Zaraki', theme: 'anime', series: 'bleach', tags: ['epeiste', 'shonen', 'force-brute', 'hot-blooded', 'excentrique'] },
  { id: 'yumichika', name: 'Yumichika Ayasegawa', theme: 'anime', series: 'bleach', tags: ['epeiste', 'shonen', 'orgueilleux', 'loyal', 'excentrique'] },
  { id: 'ikkaku', name: 'Ikkaku Madarame', theme: 'anime', series: 'bleach', tags: ['epeiste', 'shonen', 'hot-blooded', 'loyal', 'force-brute'] },
  { id: 'rangiku', name: 'Rangiku Matsumoto', theme: 'anime', series: 'bleach', tags: ['shonen', 'comique', 'loyal', 'charismatique', 'attachant'] },
  { id: 'shunsui-kyoraku', name: 'Shunsui Kyoraku', theme: 'anime', series: 'bleach', tags: ['epeiste', 'shonen', 'calme', 'excentrique', 'mentor'] },
  { id: 'jushiro-ukitake', name: 'Jushiro Ukitake', theme: 'anime', series: 'bleach', tags: ['epeiste', 'shonen', 'calme', 'mentor', 'loyal'] },
  { id: 'soifon', name: 'Soi Fon', theme: 'anime', series: 'bleach', tags: ['epeiste', 'shonen', 'discipline', 'loyal', 'determine'] },
  { id: 'mayuri-kurotsuchi', name: 'Mayuri Kurotsuchi', theme: 'anime', series: 'bleach', tags: ['shonen', 'genie', 'sombre', 'excentrique', 'manipulateur'] },
  { id: 'nemu-kurotsuchi', name: 'Nemu Kurotsuchi', theme: 'anime', series: 'bleach', tags: ['shonen', 'loyal', 'calme', 'sacrifice', 'discipline'] },
  { id: 'yamamoto', name: 'Genryusai Yamamoto', theme: 'anime', series: 'bleach', tags: ['epeiste', 'shonen', 'mentor', 'force-brute', 'discipline'] },
  { id: 'ulquiorra', name: 'Ulquiorra Cifer', theme: 'anime', series: 'bleach', tags: ['shonen', 'antagoniste', 'calme', 'sombre', 'mysterieux'] },
  { id: 'nnoitra', name: 'Nnoitra Gilga', theme: 'anime', series: 'bleach', tags: ['shonen', 'antagoniste', 'orgueilleux', 'force-brute', 'hot-blooded'] },
  { id: 'starrk', name: 'Coyote Starrk', theme: 'anime', series: 'bleach', tags: ['shonen', 'antagoniste', 'blase', 'calme', 'force-brute'] },
  { id: 'harribel', name: 'Tia Harribel', theme: 'anime', series: 'bleach', tags: ['epeiste', 'shonen', 'antagoniste', 'calme', 'loyal'] },
  { id: 'gin-ichimaru', name: 'Gin Ichimaru', theme: 'anime', series: 'bleach', tags: ['shonen', 'antagoniste', 'manipulateur', 'sarcastique', 'mysterieux'] },
  { id: 'kaname-tosen', name: 'Kaname Tosen', theme: 'anime', series: 'bleach', tags: ['epeiste', 'shonen', 'antagoniste', 'calme', 'idealiste'] },
  { id: 'isshin-kurosaki', name: 'Isshin Kurosaki', theme: 'anime', series: 'bleach', tags: ['epeiste', 'shonen', 'comique', 'mentor', 'force-brute'] },
  { id: 'yuzu-kurosaki', name: 'Yuzu Kurosaki', theme: 'anime', series: 'bleach', tags: ['shonen', 'naif', 'loyal', 'attachant', 'famille'] },
  { id: 'karin-kurosaki', name: 'Karin Kurosaki', theme: 'anime', series: 'bleach', tags: ['shonen', 'determine', 'sarcastique', 'loyal', 'famille'] },
  { id: 'chad', name: 'Yasutora Sado (Chad)', theme: 'anime', series: 'bleach', tags: ['shonen', 'calme', 'loyal', 'force-brute', 'protecteur'] },
  { id: 'nel-tu', name: 'Nelliel Tu Odelschwanck', theme: 'anime', series: 'bleach', tags: ['shonen', 'naif', 'comique', 'loyal', 'attachant'] },
  { id: 'yhwach', name: 'Yhwach', theme: 'anime', series: 'bleach', tags: ['shonen', 'antagoniste', 'manipulateur', 'genie', 'force-brute'] },
  { id: 'askin-nakk-le-vaar', name: 'Askin Nakk Le Vaar', theme: 'anime', series: 'bleach', tags: ['shonen', 'antagoniste', 'sarcastique', 'genie', 'calme'] },
  { id: 'jugram-haschwalth', name: 'Jugram Haschwalth', theme: 'anime', series: 'bleach', tags: ['shonen', 'loyal', 'calme', 'stratege', 'mysterieux'] },
  { id: 'bazz-b', name: 'Bazz-B', theme: 'anime', series: 'bleach', tags: ['shonen', 'antagoniste', 'hot-blooded', 'impulsif', 'force-brute'] },
  { id: 'candice-catnipp', name: 'Candice Catnipp', theme: 'anime', series: 'bleach', tags: ['shonen', 'antagoniste', 'hot-blooded', 'orgueilleux', 'impulsif'] },
  { id: 'nanao-ise', name: 'Nanao Ise', theme: 'anime', series: 'bleach', tags: ['shonen', 'discipline', 'loyal', 'calme', 'stratege'] },
  { id: 'momo-hinamori', name: 'Momo Hinamori', theme: 'anime', series: 'bleach', tags: ['shonen', 'loyal', 'traumatise', 'naif', 'determine'] },
  { id: 'izuru-kira', name: 'Izuru Kira', theme: 'anime', series: 'bleach', tags: ['epeiste', 'shonen', 'calme', 'loyal', 'traumatise'] },
  // Hunter x Hunter
  { id: 'gon', name: 'Gon Freecss', theme: 'anime', series: 'hunter-x-hunter', tags: ['chasseur', 'shonen', 'naif', 'protagoniste', 'determine'] },
  { id: 'killua', name: 'Killua Zoldyck', theme: 'anime', series: 'hunter-x-hunter', tags: ['chasseur', 'shonen', 'assassin', 'loyal', 'genie'] },
  { id: 'kurapika', name: 'Kurapika', theme: 'anime', series: 'hunter-x-hunter', tags: ['chasseur', 'shonen', 'vengeance', 'stratege', 'calme'] },
  { id: 'leorio', name: 'Leorio Paradinight', theme: 'anime', series: 'hunter-x-hunter', tags: ['chasseur', 'shonen', 'loyal', 'comique', 'ambitieux'] },
  { id: 'hisoka', name: 'Hisoka Morow', theme: 'anime', series: 'hunter-x-hunter', tags: ['chasseur', 'shonen', 'excentrique', 'sombre', 'genie'] },
  { id: 'chrollo', name: 'Chrollo Lucilfer', theme: 'anime', series: 'hunter-x-hunter', tags: ['shonen', 'antagoniste', 'stratege', 'calme', 'genie'] },
  { id: 'meruem', name: 'Meruem', theme: 'anime', series: 'hunter-x-hunter', tags: ['shonen', 'force-brute', 'genie', 'redemption', 'orgueilleux'] },
  { id: 'netero', name: 'Netero', theme: 'anime', series: 'hunter-x-hunter', tags: ['chasseur', 'shonen', 'mentor', 'force-brute', 'excentrique'] },
  { id: 'biscuit', name: 'Biscuit Krueger', theme: 'anime', series: 'hunter-x-hunter', tags: ['chasseur', 'shonen', 'mentor', 'comique', 'force-brute'] },
  { id: 'illumi', name: 'Illumi Zoldyck', theme: 'anime', series: 'hunter-x-hunter', tags: ['chasseur', 'shonen', 'assassin', 'manipulateur', 'sombre'] },
  { id: 'kite', name: 'Kite', theme: 'anime', series: 'hunter-x-hunter', tags: ['chasseur', 'shonen', 'calme', 'loyal', 'mentor'] },
  { id: 'ging-freecss', name: 'Ging Freecss', theme: 'anime', series: 'hunter-x-hunter', tags: ['chasseur', 'shonen', 'genie', 'mysterieux', 'blase'] },
  { id: 'pariston-hill', name: 'Pariston Hill', theme: 'anime', series: 'hunter-x-hunter', tags: ['shonen', 'manipulateur', 'excentrique', 'sarcastique', 'stratege'] },
  { id: 'silva-zoldyck', name: 'Silva Zoldyck', theme: 'anime', series: 'hunter-x-hunter', tags: ['chasseur', 'shonen', 'assassin', 'calme', 'force-brute'] },
  { id: 'zeno-zoldyck', name: 'Zeno Zoldyck', theme: 'anime', series: 'hunter-x-hunter', tags: ['chasseur', 'shonen', 'assassin', 'genie', 'calme'] },
  { id: 'kikyo-zoldyck', name: 'Kikyo Zoldyck', theme: 'anime', series: 'hunter-x-hunter', tags: ['shonen', 'sombre', 'manipulateur', 'famille', 'impulsif'] },
  { id: 'alluka-zoldyck', name: 'Alluka Zoldyck', theme: 'anime', series: 'hunter-x-hunter', tags: ['shonen', 'naif', 'loyal', 'mysterieux', 'attachant'] },
  { id: 'milluki-zoldyck', name: 'Milluki Zoldyck', theme: 'anime', series: 'hunter-x-hunter', tags: ['shonen', 'comique', 'excentrique', 'famille', 'blase'] },
  { id: 'kalluto-zoldyck', name: 'Kalluto Zoldyck', theme: 'anime', series: 'hunter-x-hunter', tags: ['chasseur', 'shonen', 'calme', 'loyal', 'mysterieux'] },
  { id: 'feitan', name: 'Feitan', theme: 'anime', series: 'hunter-x-hunter', tags: ['shonen', 'antagoniste', 'sombre', 'sarcastique', 'calme'] },
  { id: 'phinks', name: 'Phinks', theme: 'anime', series: 'hunter-x-hunter', tags: ['shonen', 'antagoniste', 'force-brute', 'sarcastique', 'loyal'] },
  { id: 'shalnark', name: 'Shalnark', theme: 'anime', series: 'hunter-x-hunter', tags: ['shonen', 'antagoniste', 'manipulateur', 'comique', 'genie'] },
  { id: 'nobunaga-hazama', name: 'Nobunaga Hazama', theme: 'anime', series: 'hunter-x-hunter', tags: ['shonen', 'antagoniste', 'hot-blooded', 'loyal', 'epeiste'] },
  { id: 'machi-komacine', name: 'Machi Komacine', theme: 'anime', series: 'hunter-x-hunter', tags: ['shonen', 'antagoniste', 'calme', 'loyal', 'discipline'] },
  { id: 'shizuku-murasaki', name: 'Shizuku Murasaki', theme: 'anime', series: 'hunter-x-hunter', tags: ['shonen', 'antagoniste', 'naif', 'calme', 'blase'] },
  { id: 'franklin-bordeau', name: 'Franklin Bordeau', theme: 'anime', series: 'hunter-x-hunter', tags: ['shonen', 'antagoniste', 'force-brute', 'loyal', 'calme'] },
  { id: 'pakunoda', name: 'Pakunoda', theme: 'anime', series: 'hunter-x-hunter', tags: ['shonen', 'antagoniste', 'loyal', 'sacrifice', 'calme'] },
  { id: 'uvogin', name: 'Uvogin', theme: 'anime', series: 'hunter-x-hunter', tags: ['shonen', 'antagoniste', 'force-brute', 'hot-blooded', 'loyal'] },
  { id: 'kortopi', name: 'Kortopi', theme: 'anime', series: 'hunter-x-hunter', tags: ['shonen', 'antagoniste', 'calme', 'mysterieux', 'naif'] },
  { id: 'bonolenov-ndongo', name: 'Bonolenov Ndongo', theme: 'anime', series: 'hunter-x-hunter', tags: ['shonen', 'antagoniste', 'mysterieux', 'calme', 'force-brute'] },
  { id: 'komugi', name: 'Komugi', theme: 'anime', series: 'hunter-x-hunter', tags: ['shonen', 'naif', 'genie', 'attachant', 'determine'] },
  { id: 'neferpitou', name: 'Neferpitou', theme: 'anime', series: 'hunter-x-hunter', tags: ['shonen', 'antagoniste', 'loyal', 'force-brute', 'sombre'] },
  { id: 'shaiapouf', name: 'Shaiapouf', theme: 'anime', series: 'hunter-x-hunter', tags: ['shonen', 'antagoniste', 'manipulateur', 'loyal', 'sombre'] },
  { id: 'menthuthuyoupi', name: 'Menthuthuyoupi', theme: 'anime', series: 'hunter-x-hunter', tags: ['shonen', 'antagoniste', 'loyal', 'force-brute', 'orgueilleux'] },
  { id: 'knuckle-bine', name: 'Knuckle Bine', theme: 'anime', series: 'hunter-x-hunter', tags: ['chasseur', 'shonen', 'hot-blooded', 'loyal', 'comique'] },
  { id: 'shoot-mcmahon', name: 'Shoot McMahon', theme: 'anime', series: 'hunter-x-hunter', tags: ['chasseur', 'shonen', 'calme', 'loyal', 'discipline'] },
  { id: 'morel-mackernasey', name: 'Morel Mackernasey', theme: 'anime', series: 'hunter-x-hunter', tags: ['chasseur', 'shonen', 'mentor', 'calme', 'sarcastique'] },
  { id: 'knov', name: 'Knov', theme: 'anime', series: 'hunter-x-hunter', tags: ['chasseur', 'shonen', 'calme', 'genie', 'mysterieux'] },
  { id: 'palm-siberia', name: 'Palm Siberia', theme: 'anime', series: 'hunter-x-hunter', tags: ['shonen', 'excentrique', 'loyal', 'traumatise', 'determine'] },
  { id: 'wing', name: 'Wing', theme: 'anime', series: 'hunter-x-hunter', tags: ['chasseur', 'shonen', 'mentor', 'calme', 'discipline'] },
  // One Punch Man
  { id: 'saitama', name: 'Saitama', theme: 'anime', series: 'one-punch-man', tags: ['combattant-corps-a-corps', 'seinen', 'blase', 'force-brute', 'comique'] },
  { id: 'genos', name: 'Genos', theme: 'anime', series: 'one-punch-man', tags: ['cyborg', 'seinen', 'loyal', 'determine', 'disciple'] },
  { id: 'sonic', name: "Speed-o'-Sound Sonic", theme: 'anime', series: 'one-punch-man', tags: ['seinen', 'rival', 'orgueilleux', 'combattant-corps-a-corps', 'impulsif'] },
  { id: 'king', name: 'King', theme: 'anime', series: 'one-punch-man', tags: ['seinen', 'comique', 'peureux', 'blase', 'mysterieux'] },
  { id: 'tatsumaki', name: 'Tatsumaki', theme: 'anime', series: 'one-punch-man', tags: ['seinen', 'super-pouvoir', 'orgueilleux', 'force-brute', 'sarcastique'] },
  { id: 'fubuki', name: 'Fubuki', theme: 'anime', series: 'one-punch-man', tags: ['seinen', 'super-pouvoir', 'stratege', 'orgueilleux', 'ambitieux'] },
  { id: 'bang', name: 'Bang', theme: 'anime', series: 'one-punch-man', tags: ['combattant-corps-a-corps', 'seinen', 'mentor', 'calme', 'discipline'] },
  { id: 'garou', name: 'Garou', theme: 'anime', series: 'one-punch-man', tags: ['seinen', 'antagoniste', 'force-brute', 'determine', 'redemption'] },
  { id: 'mumen-rider', name: 'Mumen Rider', theme: 'anime', series: 'one-punch-man', tags: ['seinen', 'courageux', 'heros-ordinaire', 'attachant', 'loyal'] },
  { id: 'boros', name: 'Boros', theme: 'anime', series: 'one-punch-man', tags: ['seinen', 'antagoniste', 'force-brute', 'conquerant', 'charismatique'] },
  // Sword Art Online
  { id: 'kirito', name: 'Kirito', theme: 'anime', series: 'sword-art-online', tags: ['epeiste', 'isekai', 'genie', 'protagoniste', 'calme'] },
  { id: 'asuna', name: 'Asuna', theme: 'anime', series: 'sword-art-online', tags: ['epeiste', 'isekai', 'determine', 'stratege', 'loyal'] },
  { id: 'sinon', name: 'Sinon', theme: 'anime', series: 'sword-art-online', tags: ['isekai', 'tireuse', 'calme', 'traumatise', 'determine'] },
  { id: 'klein', name: 'Klein', theme: 'anime', series: 'sword-art-online', tags: ['epeiste', 'isekai', 'loyal', 'comique', 'charismatique'] },
  { id: 'leafa', name: 'Leafa', theme: 'anime', series: 'sword-art-online', tags: ['epeiste', 'isekai', 'loyal', 'determine', 'attachant'] },
  { id: 'yuuki', name: 'Yuuki', theme: 'anime', series: 'sword-art-online', tags: ['epeiste', 'isekai', 'courageux', 'attachant', 'genie'] },
  { id: 'heathcliff', name: 'Heathcliff', theme: 'anime', series: 'sword-art-online', tags: ['epeiste', 'isekai', 'antagoniste', 'mysterieux', 'stratege'] },
  { id: 'silica', name: 'Silica', theme: 'anime', series: 'sword-art-online', tags: ['isekai', 'dresseur', 'timide', 'loyal', 'attachant'] },
  { id: 'lisbeth', name: 'Lisbeth', theme: 'anime', series: 'sword-art-online', tags: ['isekai', 'genie', 'loyal', 'sarcastique', 'determine'] },
  { id: 'alice-zuberg', name: 'Alice Zuberg', theme: 'anime', series: 'sword-art-online', tags: ['epeiste', 'isekai', 'determine', 'idealiste', 'courageux'] },
  // Tokyo Ghoul
  { id: 'kaneki', name: 'Ken Kaneki', theme: 'anime', series: 'tokyo-ghoul', tags: ['transformation', 'seinen', 'sombre', 'protagoniste', 'sacrifice'] },
  { id: 'touka', name: 'Touka Kirishima', theme: 'anime', series: 'tokyo-ghoul', tags: ['transformation', 'seinen', 'determine', 'loyal', 'combattant-corps-a-corps'] },
  { id: 'yomo', name: 'Renji Yomo', theme: 'anime', series: 'tokyo-ghoul', tags: ['transformation', 'seinen', 'calme', 'loyal', 'mysterieux'] },
  { id: 'nishiki', name: 'Nishiki Nishio', theme: 'anime', series: 'tokyo-ghoul', tags: ['transformation', 'seinen', 'sarcastique', 'rival', 'loyal'] },
  { id: 'juuzou', name: 'Juuzou Suzuya', theme: 'anime', series: 'tokyo-ghoul', tags: ['seinen', 'excentrique', 'traumatise', 'combattant-corps-a-corps', 'impulsif'] },
  { id: 'arima', name: 'Kishou Arima', theme: 'anime', series: 'tokyo-ghoul', tags: ['epeiste', 'seinen', 'calme', 'force-brute', 'mysterieux'] },
  { id: 'hide', name: 'Hideyoshi Nagachika', theme: 'anime', series: 'tokyo-ghoul', tags: ['seinen', 'loyal', 'comique', 'genie', 'sacrifice'] },
  { id: 'rize', name: 'Rize Kamishiro', theme: 'anime', series: 'tokyo-ghoul', tags: ['transformation', 'seinen', 'mysterieux', 'sombre', 'manipulateur'] },
  { id: 'uta', name: 'Uta', theme: 'anime', series: 'tokyo-ghoul', tags: ['transformation', 'seinen', 'excentrique', 'mysterieux', 'calme'] },
  { id: 'eto', name: 'Eto Yoshimura', theme: 'anime', series: 'tokyo-ghoul', tags: ['transformation', 'seinen', 'antagoniste', 'genie', 'manipulateur'] },
  // Cowboy Bebop
  { id: 'spike-spiegel', name: 'Spike Spiegel', theme: 'anime', series: 'cowboy-bebop', tags: ['chasseur-de-primes', 'seinen', 'sarcastique', 'passe-sombre', 'calme'] },
  { id: 'faye-valentine', name: 'Faye Valentine', theme: 'anime', series: 'cowboy-bebop', tags: ['chasseur-de-primes', 'seinen', 'sarcastique', 'independante', 'mysterieux'] },
  { id: 'jet-black', name: 'Jet Black', theme: 'anime', series: 'cowboy-bebop', tags: ['chasseur-de-primes', 'seinen', 'calme', 'mentor', 'passe-sombre'] },
  { id: 'edward-wong', name: 'Edward Wong (Ed)', theme: 'anime', series: 'cowboy-bebop', tags: ['chasseur-de-primes', 'seinen', 'excentrique', 'genie', 'comique'] },
  { id: 'ein', name: 'Ein', theme: 'anime', series: 'cowboy-bebop', tags: ['seinen', 'mysterieux', 'genie', 'attachant', 'mascotte'] },
  { id: 'vicious', name: 'Vicious', theme: 'anime', series: 'cowboy-bebop', tags: ['seinen', 'antagoniste', 'sombre', 'epeiste', 'vengeance'] },
  { id: 'julia', name: 'Julia', theme: 'anime', series: 'cowboy-bebop', tags: ['seinen', 'mysterieux', 'passe-sombre', 'calme', 'attachant'] },
  { id: 'punch', name: 'Punch', theme: 'anime', series: 'cowboy-bebop', tags: ['seinen', 'comique', 'excentrique', 'charismatique', 'orateur'] },
  { id: 'judy', name: 'Judy', theme: 'anime', series: 'cowboy-bebop', tags: ['seinen', 'comique', 'excentrique', 'charismatique', 'sarcastique'] },
  { id: 'gren', name: 'Gren', theme: 'anime', series: 'cowboy-bebop', tags: ['seinen', 'calme', 'passe-sombre', 'loyal', 'sacrifice'] },
  // Neon Genesis Evangelion
  { id: 'shinji', name: 'Shinji Ikari', theme: 'anime', series: 'evangelion', tags: ['pilote-robot', 'mecha', 'timide', 'protagoniste', 'traumatise'] },
  { id: 'rei-ayanami', name: 'Rei Ayanami', theme: 'anime', series: 'evangelion', tags: ['pilote-robot', 'mecha', 'calme', 'mysterieux', 'loyal'] },
  { id: 'asuka', name: 'Asuka Langley Soryu', theme: 'anime', series: 'evangelion', tags: ['pilote-robot', 'mecha', 'orgueilleux', 'traumatise', 'impulsif'] },
  { id: 'misato', name: 'Misato Katsuragi', theme: 'anime', series: 'evangelion', tags: ['mecha', 'stratege', 'mentor', 'passe-sombre', 'loyal'] },
  { id: 'gendo', name: 'Gendo Ikari', theme: 'anime', series: 'evangelion', tags: ['mecha', 'antagoniste', 'manipulateur', 'sombre', 'mysterieux'] },
  { id: 'ritsuko', name: 'Ritsuko Akagi', theme: 'anime', series: 'evangelion', tags: ['mecha', 'genie', 'calme', 'traumatise', 'mysterieux'] },
  { id: 'kaworu', name: 'Kaworu Nagisa', theme: 'anime', series: 'evangelion', tags: ['pilote-robot', 'mecha', 'mysterieux', 'calme', 'sacrifice'] },
  { id: 'toji', name: 'Toji Suzuhara', theme: 'anime', series: 'evangelion', tags: ['pilote-robot', 'mecha', 'loyal', 'hot-blooded', 'sacrifice'] },
  { id: 'kensuke', name: 'Kensuke Aida', theme: 'anime', series: 'evangelion', tags: ['mecha', 'comique', 'naif', 'loyal', 'excentrique'] },
  { id: 'kaji', name: 'Ryoji Kaji', theme: 'anime', series: 'evangelion', tags: ['mecha', 'agent-secret', 'charismatique', 'mysterieux', 'sacrifice'] },
  // Pokémon
  { id: 'ash-ketchum', name: 'Ash Ketchum', theme: 'anime', series: 'pokemon', tags: ['dresseur', 'enfance', 'determine', 'protagoniste', 'hot-blooded'] },
  { id: 'pikachu', name: 'Pikachu', theme: 'anime', series: 'pokemon', tags: ['enfance', 'loyal', 'mascotte', 'super-pouvoir', 'attachant'] },
  { id: 'misty', name: 'Misty', theme: 'anime', series: 'pokemon', tags: ['dresseur', 'enfance', 'hot-blooded', 'loyal', 'determine'] },
  { id: 'brock', name: 'Brock', theme: 'anime', series: 'pokemon', tags: ['dresseur', 'enfance', 'loyal', 'seducteur', 'comique'] },
  { id: 'jessie', name: 'Jessie', theme: 'anime', series: 'pokemon', tags: ['enfance', 'comique', 'ambitieux', 'loyal', 'excentrique'] },
  { id: 'james', name: 'James', theme: 'anime', series: 'pokemon', tags: ['enfance', 'comique', 'loyal', 'peureux', 'excentrique'] },
  { id: 'professor-oak', name: 'Professeur Chen', theme: 'anime', series: 'pokemon', tags: ['enfance', 'mentor', 'genie', 'calme', 'sage'] },
  { id: 'gary-oak', name: 'Gary Oak', theme: 'anime', series: 'pokemon', tags: ['dresseur', 'enfance', 'rival', 'orgueilleux', 'genie'] },
  { id: 'may', name: 'May', theme: 'anime', series: 'pokemon', tags: ['dresseur', 'enfance', 'determine', 'loyal', 'attachant'] },
  { id: 'dawn', name: 'Dawn', theme: 'anime', series: 'pokemon', tags: ['dresseur', 'enfance', 'determine', 'ambitieux', 'attachant'] },
  // Spy x Family
  { id: 'loid-forger', name: 'Loid Forger', theme: 'anime', series: 'spy-x-family', tags: ['agent-secret', 'seinen', 'stratege', 'calme', 'famille'] },
  { id: 'anya-forger', name: 'Anya Forger', theme: 'anime', series: 'spy-x-family', tags: ['enfance', 'seinen', 'comique', 'super-pouvoir', 'famille'] },
  { id: 'yor-forger', name: 'Yor Forger', theme: 'anime', series: 'spy-x-family', tags: ['assassin', 'seinen', 'famille', 'calme', 'force-brute'] },
  { id: 'bond-forger', name: 'Bond Forger', theme: 'anime', series: 'spy-x-family', tags: ['enfance', 'seinen', 'famille', 'loyal', 'mascotte'] },
  { id: 'damian', name: 'Damian Desmond', theme: 'anime', series: 'spy-x-family', tags: ['enfance', 'seinen', 'orgueilleux', 'rival', 'timide'] },
  { id: 'fiona', name: 'Fiona Frost', theme: 'anime', series: 'spy-x-family', tags: ['agent-secret', 'seinen', 'calme', 'stratege', 'rival'] },
  { id: 'franky-franklin', name: 'Franky Franklin', theme: 'anime', series: 'spy-x-family', tags: ['agent-secret', 'seinen', 'comique', 'loyal', 'genie'] },
  { id: 'yuri-briar', name: 'Yuri Briar', theme: 'anime', series: 'spy-x-family', tags: ['agent-secret', 'seinen', 'famille', 'impulsif', 'loyal'] },
  { id: 'sylvia', name: 'Sylvia Sherwood', theme: 'anime', series: 'spy-x-family', tags: ['agent-secret', 'seinen', 'stratege', 'calme', 'mysterieux'] },
  { id: 'becky', name: 'Becky Blackbell', theme: 'anime', series: 'spy-x-family', tags: ['enfance', 'seinen', 'loyal', 'comique', 'attachant'] },
  // Chainsaw Man
  { id: 'denji', name: 'Denji', theme: 'anime', series: 'chainsaw-man', tags: ['transformation', 'seinen', 'naif', 'protagoniste', 'impulsif'] },
  { id: 'power', name: 'Power', theme: 'anime', series: 'chainsaw-man', tags: ['transformation', 'seinen', 'comique', 'orgueilleux', 'loyal'] },
  { id: 'aki-hayakawa', name: 'Aki Hayakawa', theme: 'anime', series: 'chainsaw-man', tags: ['seinen', 'calme', 'vengeance', 'loyal', 'sacrifice'] },
  { id: 'makima', name: 'Makima', theme: 'anime', series: 'chainsaw-man', tags: ['seinen', 'antagoniste', 'manipulateur', 'calme', 'mysterieux'] },
  { id: 'kobeni', name: 'Kobeni Higashiyama', theme: 'anime', series: 'chainsaw-man', tags: ['seinen', 'peureux', 'comique', 'traumatise', 'loyal'] },
  { id: 'himeno', name: 'Himeno', theme: 'anime', series: 'chainsaw-man', tags: ['seinen', 'sarcastique', 'loyal', 'sacrifice', 'independante'] },
  { id: 'angel-devil', name: 'Angel Devil', theme: 'anime', series: 'chainsaw-man', tags: ['seinen', 'blase', 'mysterieux', 'loyal', 'naif'] },
  { id: 'reze', name: 'Reze', theme: 'anime', series: 'chainsaw-man', tags: ['seinen', 'manipulateur', 'mysterieux', 'force-brute', 'attachant'] },
  { id: 'quanxi', name: 'Quanxi', theme: 'anime', series: 'chainsaw-man', tags: ['seinen', 'force-brute', 'blase', 'independante', 'mysterieux'] },
  { id: 'kishibe', name: 'Kishibe', theme: 'anime', series: 'chainsaw-man', tags: ['seinen', 'mentor', 'force-brute', 'calme', 'excentrique'] },
  // Code Geass
  { id: 'lelouch', name: 'Lelouch Lamperouge', theme: 'anime', series: 'code-geass', tags: ['stratege', 'mecha', 'genie', 'antagoniste', 'masque'] },
  { id: 'suzaku', name: 'Suzaku Kururugi', theme: 'anime', series: 'code-geass', tags: ['pilote-robot', 'mecha', 'loyal', 'rival', 'idealiste'] },
  { id: 'cc', name: 'C.C.', theme: 'anime', series: 'code-geass', tags: ['mecha', 'mysterieux', 'immortel', 'sarcastique', 'calme'] },
  { id: 'kallen', name: 'Kallen Kozuki', theme: 'anime', series: 'code-geass', tags: ['pilote-robot', 'mecha', 'determine', 'loyal', 'hot-blooded'] },
  { id: 'nunnally', name: 'Nunnally Lamperouge', theme: 'anime', series: 'code-geass', tags: ['mecha', 'famille', 'idealiste', 'attachant', 'sacrifice'] },
  { id: 'todoh', name: 'Todoh Kyoshiro', theme: 'anime', series: 'code-geass', tags: ['pilote-robot', 'mecha', 'loyal', 'discipline', 'mentor'] },
  { id: 'jeremiah', name: 'Jeremiah Gottwald', theme: 'anime', series: 'code-geass', tags: ['pilote-robot', 'mecha', 'loyal', 'redemption', 'determine'] },
  { id: 'rolo', name: 'Rolo Lamperouge', theme: 'anime', series: 'code-geass', tags: ['mecha', 'assassin', 'famille', 'traumatise', 'loyal'] },
  { id: 'milly', name: 'Milly Ashford', theme: 'anime', series: 'code-geass', tags: ['mecha', 'comique', 'charismatique', 'excentrique', 'loyal'] },
  { id: 'schneizel', name: 'Schneizel el Britannia', theme: 'anime', series: 'code-geass', tags: ['mecha', 'stratege', 'genie', 'calme', 'ambitieux'] },

  // Films
  { id: 'luke-skywalker', name: 'Luke Skywalker', theme: 'films', tags: ['chevalier', 'science-fiction', 'heros', 'mentor-guide', 'epeiste'] },
  { id: 'dark-vador', name: 'Dark Vador', theme: 'films', tags: ['science-fiction', 'antagoniste', 'guerrier', 'masque', 'redemption'] },
  { id: 'iron-man', name: 'Tony Stark', theme: 'films', tags: ['super-heros', 'science-fiction', 'genie', 'riche', 'sarcastique'] },
  { id: 'batman', name: 'Bruce Wayne', theme: 'films', tags: ['super-heros', 'riche', 'vigilante', 'sombre', 'genie'] },
  { id: 'indiana-jones', name: 'Indiana Jones', theme: 'films', tags: ['aventurier', 'archeologue', 'action', 'charismatique', 'annees-30'] },
  { id: 'james-bond', name: 'James Bond', theme: 'films', tags: ['espion', 'action', 'charismatique', 'epoque-moderne', 'seducteur'] },
  { id: 'forrest-gump', name: 'Forrest Gump', theme: 'films', tags: ['drame', 'naif', 'heros-ordinaire', 'americana', 'attachant'] },
  { id: 'rocky', name: 'Rocky Balboa', theme: 'films', tags: ['drame', 'boxeur', 'heros-ordinaire', 'determine', 'americana'] },
  { id: 'gandalf', name: 'Gandalf', theme: 'films', tags: ['mage', 'fantasy', 'mentor', 'sage', 'epique'] },
  { id: 'dumbledore', name: 'Dumbledore', theme: 'films', tags: ['mage', 'fantasy', 'mentor', 'sage', 'mysterieux'] },
  { id: 'jack-sparrow', name: 'Jack Sparrow', theme: 'films', tags: ['pirate', 'aventurier', 'action', 'excentrique', 'charismatique'] },
  { id: 'katniss', name: 'Katniss Everdeen', theme: 'films', tags: ['heros-ordinaire', 'action', 'determine', 'dystopie', 'archere'] },
];
