import type { Character } from './types';

export const CHARACTERS: Character[] = [
  // Histoire
  { id: 'alexandre-le-grand', name: 'Alexandre le Grand', theme: 'histoire', tags: ['conquerant', 'antiquite', 'militaire', 'empire', 'stratege'] },
  { id: 'genghis-khan', name: 'Genghis Khan', theme: 'histoire', tags: ['conquerant', 'moyen-age', 'militaire', 'empire', 'stratege'] },
  { id: 'napoleon', name: 'Napoléon Bonaparte', theme: 'histoire', tags: ['conquerant', 'epoque-moderne', 'militaire', 'empire', 'stratege'] },
  { id: 'jules-cesar', name: 'Jules César', theme: 'histoire', tags: ['conquerant', 'antiquite', 'militaire', 'empire', 'politique'] },
  { id: 'cleopatre', name: 'Cléopâtre', theme: 'histoire', tags: ['antiquite', 'politique', 'egypte', 'diplomate', 'controverse'] },
  { id: 'leonard-de-vinci', name: 'Léonard de Vinci', theme: 'histoire', tags: ['renaissance', 'art', 'science', 'inventeur', 'visionnaire'] },
  { id: 'einstein', name: 'Albert Einstein', theme: 'histoire', tags: ['science', 'xxe-siecle', 'physique', 'visionnaire', 'pacifiste'] },
  { id: 'marie-curie', name: 'Marie Curie', theme: 'histoire', tags: ['science', 'xxe-siecle', 'physique', 'chimie', 'pionniere'] },
  { id: 'gandhi', name: 'Gandhi', theme: 'histoire', tags: ['xxe-siecle', 'politique', 'pacifiste', 'activiste', 'philosophe'] },
  { id: 'mlk', name: 'Martin Luther King', theme: 'histoire', tags: ['xxe-siecle', 'politique', 'pacifiste', 'activiste', 'orateur'] },
  { id: 'colomb', name: 'Christophe Colomb', theme: 'histoire', tags: ['explorateur', 'renaissance', 'navigateur', 'controverse', 'decouverte'] },
  { id: 'marco-polo', name: 'Marco Polo', theme: 'histoire', tags: ['explorateur', 'moyen-age', 'navigateur', 'commercant', 'decouverte'] },

  // Anime -- 20 series, 10 characters each
  // One Piece
  { id: 'zoro', name: 'Roronoa Zoro', theme: 'anime', series: 'one-piece', tags: ['epeiste', 'pirate', 'shonen', 'determine', 'force-brute'] },
  { id: 'luffy', name: 'Monkey D. Luffy', theme: 'anime', series: 'one-piece', tags: ['pirate', 'shonen', 'hot-blooded', 'determine', 'protagoniste'] },
  { id: 'nami', name: 'Nami', theme: 'anime', series: 'one-piece', tags: ['pirate', 'shonen', 'stratege', 'navigateur', 'avide'] },
  { id: 'sanji', name: 'Sanji', theme: 'anime', series: 'one-piece', tags: ['pirate', 'shonen', 'combattant-corps-a-corps', 'charismatique', 'loyal'] },
  { id: 'nico-robin', name: 'Nico Robin', theme: 'anime', series: 'one-piece', tags: ['pirate', 'shonen', 'calme', 'mysterieux', 'genie'] },
  { id: 'chopper', name: 'Tony Tony Chopper', theme: 'anime', series: 'one-piece', tags: ['pirate', 'shonen', 'naif', 'attachant', 'loyal'] },
  { id: 'usopp', name: 'Usopp', theme: 'anime', series: 'one-piece', tags: ['pirate', 'shonen', 'peureux', 'comique', 'loyal'] },
  { id: 'franky', name: 'Franky', theme: 'anime', series: 'one-piece', tags: ['pirate', 'shonen', 'cyborg', 'comique', 'loyal'] },
  { id: 'brook', name: 'Brook', theme: 'anime', series: 'one-piece', tags: ['pirate', 'shonen', 'comique', 'loyal', 'epeiste'] },
  { id: 'trafalgar-law', name: 'Trafalgar Law', theme: 'anime', series: 'one-piece', tags: ['pirate', 'shonen', 'calme', 'stratege', 'rival'] },
  // Naruto
  { id: 'sasuke', name: 'Sasuke Uchiha', theme: 'anime', series: 'naruto', tags: ['ninja', 'shonen', 'vengeance', 'determine', 'rival'] },
  { id: 'naruto', name: 'Naruto Uzumaki', theme: 'anime', series: 'naruto', tags: ['ninja', 'shonen', 'determine', 'hot-blooded', 'protagoniste'] },
  { id: 'itachi', name: 'Itachi Uchiha', theme: 'anime', series: 'naruto', tags: ['ninja', 'shonen', 'stratege', 'sacrifice', 'calme'] },
  { id: 'sakura', name: 'Sakura Haruno', theme: 'anime', series: 'naruto', tags: ['ninja', 'shonen', 'determine', 'loyal', 'stratege'] },
  { id: 'kakashi', name: 'Kakashi Hatake', theme: 'anime', series: 'naruto', tags: ['ninja', 'shonen', 'calme', 'mentor', 'genie'] },
  { id: 'hinata', name: 'Hinata Hyuga', theme: 'anime', series: 'naruto', tags: ['ninja', 'shonen', 'timide', 'loyal', 'determine'] },
  { id: 'gaara', name: 'Gaara', theme: 'anime', series: 'naruto', tags: ['ninja', 'shonen', 'sombre', 'force-brute', 'redemption'] },
  { id: 'jiraiya', name: 'Jiraiya', theme: 'anime', series: 'naruto', tags: ['ninja', 'shonen', 'mentor', 'comique', 'sacrifice'] },
  { id: 'rock-lee', name: 'Rock Lee', theme: 'anime', series: 'naruto', tags: ['ninja', 'shonen', 'determine', 'hot-blooded', 'loyal'] },
  { id: 'shikamaru', name: 'Shikamaru Nara', theme: 'anime', series: 'naruto', tags: ['ninja', 'shonen', 'stratege', 'blase', 'genie'] },
  // Dragon Ball
  { id: 'goku', name: 'Goku', theme: 'anime', series: 'dragon-ball', tags: ['combattant-corps-a-corps', 'shonen', 'hot-blooded', 'force-brute', 'protagoniste'] },
  { id: 'vegeta', name: 'Vegeta', theme: 'anime', series: 'dragon-ball', tags: ['combattant-corps-a-corps', 'shonen', 'rival', 'force-brute', 'orgueilleux'] },
  { id: 'piccolo', name: 'Piccolo', theme: 'anime', series: 'dragon-ball', tags: ['combattant-corps-a-corps', 'shonen', 'mentor', 'calme', 'redemption'] },
  { id: 'gohan', name: 'Gohan', theme: 'anime', series: 'dragon-ball', tags: ['combattant-corps-a-corps', 'shonen', 'determine', 'loyal', 'genie'] },
  { id: 'bulma', name: 'Bulma', theme: 'anime', series: 'dragon-ball', tags: ['shonen', 'genie', 'stratege', 'sarcastique', 'independante'] },
  { id: 'krillin', name: 'Krillin', theme: 'anime', series: 'dragon-ball', tags: ['combattant-corps-a-corps', 'shonen', 'loyal', 'comique', 'courageux'] },
  { id: 'frieza', name: 'Frieza', theme: 'anime', series: 'dragon-ball', tags: ['shonen', 'antagoniste', 'sombre', 'genie', 'force-brute'] },
  { id: 'trunks', name: 'Trunks', theme: 'anime', series: 'dragon-ball', tags: ['combattant-corps-a-corps', 'shonen', 'determine', 'loyal', 'sacrifice'] },
  { id: 'master-roshi', name: 'Master Roshi', theme: 'anime', series: 'dragon-ball', tags: ['shonen', 'mentor', 'comique', 'genie', 'excentrique'] },
  { id: 'beerus', name: 'Beerus', theme: 'anime', series: 'dragon-ball', tags: ['shonen', 'force-brute', 'orgueilleux', 'mysterieux', 'impulsif'] },
  // Death Note
  { id: 'light', name: 'Light Yagami', theme: 'anime', series: 'death-note', tags: ['stratege', 'seinen', 'antagoniste', 'manipulateur', 'genie'] },
  { id: 'l', name: 'L', theme: 'anime', series: 'death-note', tags: ['stratege', 'seinen', 'genie', 'detective', 'calme'] },
  { id: 'misa-amane', name: 'Misa Amane', theme: 'anime', series: 'death-note', tags: ['seinen', 'loyal', 'impulsif', 'attachant', 'manipulateur'] },
  { id: 'ryuk', name: 'Ryuk', theme: 'anime', series: 'death-note', tags: ['seinen', 'mysterieux', 'comique', 'blase', 'immortel'] },
  { id: 'near', name: 'Near', theme: 'anime', series: 'death-note', tags: ['stratege', 'seinen', 'genie', 'detective', 'calme'] },
  { id: 'mello', name: 'Mello', theme: 'anime', series: 'death-note', tags: ['stratege', 'seinen', 'impulsif', 'rival', 'determine'] },
  { id: 'soichiro-yagami', name: 'Soichiro Yagami', theme: 'anime', series: 'death-note', tags: ['seinen', 'loyal', 'detective', 'sacrifice', 'stratege'] },
  { id: 'teru-mikami', name: 'Teru Mikami', theme: 'anime', series: 'death-note', tags: ['seinen', 'sombre', 'loyal', 'manipulateur', 'genie'] },
  { id: 'rem', name: 'Rem', theme: 'anime', series: 'death-note', tags: ['seinen', 'mysterieux', 'sacrifice', 'loyal', 'immortel'] },
  { id: 'matsuda', name: 'Matsuda', theme: 'anime', series: 'death-note', tags: ['seinen', 'naif', 'comique', 'loyal', 'detective'] },
  // L'Attaque des Titans
  { id: 'levi', name: 'Levi Ackerman', theme: 'anime', series: 'attack-on-titan', tags: ['epeiste', 'seinen', 'force-brute', 'calme', 'capitaine'] },
  { id: 'erwin', name: 'Erwin Smith', theme: 'anime', series: 'attack-on-titan', tags: ['seinen', 'stratege', 'capitaine', 'sacrifice', 'visionnaire'] },
  { id: 'eren-yeager', name: 'Eren Yeager', theme: 'anime', series: 'attack-on-titan', tags: ['seinen', 'hot-blooded', 'transformation', 'vengeance', 'protagoniste'] },
  { id: 'mikasa', name: 'Mikasa Ackerman', theme: 'anime', series: 'attack-on-titan', tags: ['epeiste', 'seinen', 'loyal', 'determine', 'force-brute'] },
  { id: 'armin', name: 'Armin Arlert', theme: 'anime', series: 'attack-on-titan', tags: ['seinen', 'stratege', 'genie', 'loyal', 'sacrifice'] },
  { id: 'historia', name: 'Historia Reiss', theme: 'anime', series: 'attack-on-titan', tags: ['seinen', 'loyal', 'determine', 'sacrifice', 'redemption'] },
  { id: 'reiner', name: 'Reiner Braun', theme: 'anime', series: 'attack-on-titan', tags: ['seinen', 'transformation', 'sombre', 'sacrifice', 'traumatise'] },
  { id: 'annie', name: 'Annie Leonhart', theme: 'anime', series: 'attack-on-titan', tags: ['seinen', 'transformation', 'calme', 'mysterieux', 'combattant-corps-a-corps'] },
  { id: 'hange', name: 'Hange Zoe', theme: 'anime', series: 'attack-on-titan', tags: ['seinen', 'genie', 'excentrique', 'stratege', 'loyal'] },
  { id: 'zeke-yeager', name: 'Zeke Yeager', theme: 'anime', series: 'attack-on-titan', tags: ['seinen', 'stratege', 'transformation', 'manipulateur', 'antagoniste'] },
  // Fullmetal Alchemist
  { id: 'edward-elric', name: 'Edward Elric', theme: 'anime', series: 'fullmetal-alchemist', tags: ['alchimiste', 'shonen', 'determine', 'hot-blooded', 'protagoniste'] },
  { id: 'alphonse-elric', name: 'Alphonse Elric', theme: 'anime', series: 'fullmetal-alchemist', tags: ['alchimiste', 'shonen', 'loyal', 'sacrifice', 'protagoniste'] },
  { id: 'roy-mustang', name: 'Roy Mustang', theme: 'anime', series: 'fullmetal-alchemist', tags: ['alchimiste', 'shonen', 'stratege', 'charismatique', 'ambitieux'] },
  { id: 'riza-hawkeye', name: 'Riza Hawkeye', theme: 'anime', series: 'fullmetal-alchemist', tags: ['shonen', 'loyal', 'calme', 'determine', 'tireuse'] },
  { id: 'winry-rockbell', name: 'Winry Rockbell', theme: 'anime', series: 'fullmetal-alchemist', tags: ['shonen', 'genie', 'loyal', 'attachant', 'determine'] },
  { id: 'alex-armstrong', name: 'Alex Louis Armstrong', theme: 'anime', series: 'fullmetal-alchemist', tags: ['alchimiste', 'shonen', 'force-brute', 'comique', 'loyal'] },
  { id: 'scar', name: 'Scar', theme: 'anime', series: 'fullmetal-alchemist', tags: ['shonen', 'vengeance', 'sombre', 'force-brute', 'redemption'] },
  { id: 'king-bradley', name: 'King Bradley', theme: 'anime', series: 'fullmetal-alchemist', tags: ['shonen', 'antagoniste', 'epeiste', 'stratege', 'masque'] },
  { id: 'maes-hughes', name: 'Maes Hughes', theme: 'anime', series: 'fullmetal-alchemist', tags: ['shonen', 'loyal', 'comique', 'famille', 'sacrifice'] },
  { id: 'envy', name: 'Envy', theme: 'anime', series: 'fullmetal-alchemist', tags: ['shonen', 'antagoniste', 'transformation', 'manipulateur', 'sombre'] },
  // My Hero Academia
  { id: 'deku', name: 'Izuku Midoriya', theme: 'anime', series: 'my-hero-academia', tags: ['super-pouvoir', 'shonen', 'determine', 'protagoniste', 'courageux'] },
  { id: 'bakugo', name: 'Katsuki Bakugo', theme: 'anime', series: 'my-hero-academia', tags: ['super-pouvoir', 'shonen', 'hot-blooded', 'rival', 'orgueilleux'] },
  { id: 'all-might', name: 'All Might', theme: 'anime', series: 'my-hero-academia', tags: ['super-pouvoir', 'shonen', 'mentor', 'force-brute', 'sacrifice'] },
  { id: 'todoroki', name: 'Shoto Todoroki', theme: 'anime', series: 'my-hero-academia', tags: ['super-pouvoir', 'shonen', 'calme', 'traumatise', 'determine'] },
  { id: 'uraraka', name: 'Ochaco Uraraka', theme: 'anime', series: 'my-hero-academia', tags: ['super-pouvoir', 'shonen', 'loyal', 'determine', 'attachant'] },
  { id: 'iida', name: 'Tenya Iida', theme: 'anime', series: 'my-hero-academia', tags: ['super-pouvoir', 'shonen', 'loyal', 'stratege', 'discipline'] },
  { id: 'shigaraki', name: 'Tomura Shigaraki', theme: 'anime', series: 'my-hero-academia', tags: ['super-pouvoir', 'shonen', 'antagoniste', 'sombre', 'traumatise'] },
  { id: 'kirishima', name: 'Eijiro Kirishima', theme: 'anime', series: 'my-hero-academia', tags: ['super-pouvoir', 'shonen', 'loyal', 'courageux', 'hot-blooded'] },
  { id: 'kaminari', name: 'Denki Kaminari', theme: 'anime', series: 'my-hero-academia', tags: ['super-pouvoir', 'shonen', 'comique', 'loyal', 'naif'] },
  { id: 'yaoyorozu', name: 'Momo Yaoyorozu', theme: 'anime', series: 'my-hero-academia', tags: ['super-pouvoir', 'shonen', 'genie', 'stratege', 'calme'] },
  // Demon Slayer
  { id: 'tanjiro', name: 'Tanjiro Kamado', theme: 'anime', series: 'demon-slayer', tags: ['epeiste', 'shonen', 'determine', 'protagoniste', 'loyal'] },
  { id: 'nezuko', name: 'Nezuko Kamado', theme: 'anime', series: 'demon-slayer', tags: ['transformation', 'shonen', 'loyal', 'sacrifice', 'protecteur'] },
  { id: 'zenitsu', name: 'Zenitsu Agatsuma', theme: 'anime', series: 'demon-slayer', tags: ['epeiste', 'shonen', 'peureux', 'comique', 'loyal'] },
  { id: 'inosuke', name: 'Inosuke Hashibira', theme: 'anime', series: 'demon-slayer', tags: ['epeiste', 'shonen', 'impulsif', 'force-brute', 'comique'] },
  { id: 'giyu', name: 'Giyu Tomioka', theme: 'anime', series: 'demon-slayer', tags: ['epeiste', 'shonen', 'calme', 'solitaire', 'loyal'] },
  { id: 'shinobu', name: 'Shinobu Kocho', theme: 'anime', series: 'demon-slayer', tags: ['epeiste', 'shonen', 'calme', 'vengeance', 'sarcastique'] },
  { id: 'rengoku', name: 'Kyojuro Rengoku', theme: 'anime', series: 'demon-slayer', tags: ['epeiste', 'shonen', 'hot-blooded', 'mentor', 'sacrifice'] },
  { id: 'muzan', name: 'Muzan Kibutsuji', theme: 'anime', series: 'demon-slayer', tags: ['shonen', 'antagoniste', 'transformation', 'sombre', 'immortel'] },
  { id: 'tengen', name: 'Tengen Uzui', theme: 'anime', series: 'demon-slayer', tags: ['epeiste', 'shonen', 'excentrique', 'force-brute', 'charismatique'] },
  { id: 'akaza', name: 'Akaza', theme: 'anime', series: 'demon-slayer', tags: ['shonen', 'antagoniste', 'force-brute', 'transformation', 'traumatise'] },
  // Jujutsu Kaisen
  { id: 'yuji-itadori', name: 'Yuji Itadori', theme: 'anime', series: 'jujutsu-kaisen', tags: ['exorciste', 'shonen', 'determine', 'protagoniste', 'sacrifice'] },
  { id: 'gojo', name: 'Satoru Gojo', theme: 'anime', series: 'jujutsu-kaisen', tags: ['exorciste', 'shonen', 'genie', 'mentor', 'sarcastique'] },
  { id: 'megumi', name: 'Megumi Fushiguro', theme: 'anime', series: 'jujutsu-kaisen', tags: ['exorciste', 'shonen', 'calme', 'stratege', 'loyal'] },
  { id: 'nobara', name: 'Nobara Kugisaki', theme: 'anime', series: 'jujutsu-kaisen', tags: ['exorciste', 'shonen', 'determine', 'impulsif', 'sarcastique'] },
  { id: 'sukuna', name: 'Sukuna', theme: 'anime', series: 'jujutsu-kaisen', tags: ['exorciste', 'shonen', 'antagoniste', 'sombre', 'force-brute'] },
  { id: 'nanami', name: 'Nanami Kento', theme: 'anime', series: 'jujutsu-kaisen', tags: ['exorciste', 'shonen', 'calme', 'discipline', 'blase'] },
  { id: 'maki', name: 'Maki Zenin', theme: 'anime', series: 'jujutsu-kaisen', tags: ['exorciste', 'shonen', 'determine', 'force-brute', 'rival'] },
  { id: 'toge', name: 'Toge Inumaki', theme: 'anime', series: 'jujutsu-kaisen', tags: ['exorciste', 'shonen', 'calme', 'loyal', 'mysterieux'] },
  { id: 'yuta', name: 'Yuta Okkotsu', theme: 'anime', series: 'jujutsu-kaisen', tags: ['exorciste', 'shonen', 'genie', 'loyal', 'timide'] },
  { id: 'mahito', name: 'Mahito', theme: 'anime', series: 'jujutsu-kaisen', tags: ['exorciste', 'shonen', 'antagoniste', 'manipulateur', 'sombre'] },
  // Bleach
  { id: 'ichigo', name: 'Ichigo Kurosaki', theme: 'anime', series: 'bleach', tags: ['epeiste', 'shonen', 'hot-blooded', 'protagoniste', 'determine'] },
  { id: 'rukia', name: 'Rukia Kuchiki', theme: 'anime', series: 'bleach', tags: ['epeiste', 'shonen', 'calme', 'mentor', 'loyal'] },
  { id: 'orihime', name: 'Orihime Inoue', theme: 'anime', series: 'bleach', tags: ['shonen', 'loyal', 'attachant', 'naif', 'super-pouvoir'] },
  { id: 'uryu', name: 'Uryu Ishida', theme: 'anime', series: 'bleach', tags: ['shonen', 'orgueilleux', 'stratege', 'rival', 'discipline'] },
  { id: 'renji', name: 'Renji Abarai', theme: 'anime', series: 'bleach', tags: ['epeiste', 'shonen', 'loyal', 'hot-blooded', 'determine'] },
  { id: 'urahara', name: 'Kisuke Urahara', theme: 'anime', series: 'bleach', tags: ['shonen', 'genie', 'mysterieux', 'sarcastique', 'mentor'] },
  { id: 'byakuya', name: 'Byakuya Kuchiki', theme: 'anime', series: 'bleach', tags: ['epeiste', 'shonen', 'calme', 'orgueilleux', 'discipline'] },
  { id: 'toshiro', name: 'Toshiro Hitsugaya', theme: 'anime', series: 'bleach', tags: ['epeiste', 'shonen', 'calme', 'genie', 'determine'] },
  { id: 'grimmjow', name: 'Grimmjow Jaegerjaquez', theme: 'anime', series: 'bleach', tags: ['shonen', 'antagoniste', 'hot-blooded', 'force-brute', 'orgueilleux'] },
  { id: 'aizen', name: 'Sosuke Aizen', theme: 'anime', series: 'bleach', tags: ['shonen', 'antagoniste', 'manipulateur', 'genie', 'calme'] },
  // Hunter x Hunter
  { id: 'gon', name: 'Gon Freecss', theme: 'anime', series: 'hunter-x-hunter', tags: ['chasseur', 'shonen', 'naif', 'protagoniste', 'determine'] },
  { id: 'killua', name: 'Killua Zoldyck', theme: 'anime', series: 'hunter-x-hunter', tags: ['chasseur', 'shonen', 'assassin', 'loyal', 'genie'] },
  { id: 'kurapika', name: 'Kurapika', theme: 'anime', series: 'hunter-x-hunter', tags: ['chasseur', 'shonen', 'vengeance', 'stratege', 'calme'] },
  { id: 'leorio', name: 'Leorio Paradinight', theme: 'anime', series: 'hunter-x-hunter', tags: ['chasseur', 'shonen', 'loyal', 'comique', 'ambitieux'] },
  { id: 'hisoka', name: 'Hisoka Morow', theme: 'anime', series: 'hunter-x-hunter', tags: ['chasseur', 'shonen', 'excentrique', 'sombre', 'genie'] },
  { id: 'chrollo', name: 'Chrollo Lucilfer', theme: 'anime', series: 'hunter-x-hunter', tags: ['shonen', 'antagoniste', 'stratege', 'calme', 'genie'] },
  { id: 'meruem', name: 'Meruem', theme: 'anime', series: 'hunter-x-hunter', tags: ['shonen', 'force-brute', 'genie', 'redemption', 'orgueilleux'] },
  { id: 'netero', name: 'Netero', theme: 'anime', series: 'hunter-x-hunter', tags: ['chasseur', 'shonen', 'mentor', 'force-brute', 'excentrique'] },
  { id: 'biscuit', name: 'Biscuit Krueger', theme: 'anime', series: 'hunter-x-hunter', tags: ['chasseur', 'shonen', 'mentor', 'comique', 'force-brute'] },
  { id: 'illumi', name: 'Illumi Zoldyck', theme: 'anime', series: 'hunter-x-hunter', tags: ['chasseur', 'shonen', 'assassin', 'manipulateur', 'sombre'] },
  // One Punch Man
  { id: 'saitama', name: 'Saitama', theme: 'anime', series: 'one-punch-man', tags: ['combattant-corps-a-corps', 'seinen', 'blase', 'force-brute', 'comique'] },
  { id: 'genos', name: 'Genos', theme: 'anime', series: 'one-punch-man', tags: ['cyborg', 'seinen', 'loyal', 'determine', 'disciple'] },
  { id: 'sonic', name: "Speed-o'-Sound Sonic", theme: 'anime', series: 'one-punch-man', tags: ['seinen', 'rival', 'orgueilleux', 'combattant-corps-a-corps', 'impulsif'] },
  { id: 'king', name: 'King', theme: 'anime', series: 'one-punch-man', tags: ['seinen', 'comique', 'peureux', 'blase', 'mysterieux'] },
  { id: 'tatsumaki', name: 'Tatsumaki', theme: 'anime', series: 'one-punch-man', tags: ['seinen', 'super-pouvoir', 'orgueilleux', 'force-brute', 'sarcastique'] },
  { id: 'fubuki', name: 'Fubuki', theme: 'anime', series: 'one-punch-man', tags: ['seinen', 'super-pouvoir', 'stratege', 'orgueilleux', 'ambitieux'] },
  { id: 'bang', name: 'Bang', theme: 'anime', series: 'one-punch-man', tags: ['combattant-corps-a-corps', 'seinen', 'mentor', 'calme', 'discipline'] },
  { id: 'garou', name: 'Garou', theme: 'anime', series: 'one-punch-man', tags: ['seinen', 'antagoniste', 'force-brute', 'determine', 'redemption'] },
  { id: 'mumen-rider', name: 'Mumen Rider', theme: 'anime', series: 'one-punch-man', tags: ['seinen', 'courageux', 'heros-ordinaire', 'attachant', 'loyal'] },
  { id: 'boros', name: 'Boros', theme: 'anime', series: 'one-punch-man', tags: ['seinen', 'antagoniste', 'force-brute', 'conquerant', 'charismatique'] },
  // Sword Art Online
  { id: 'kirito', name: 'Kirito', theme: 'anime', series: 'sword-art-online', tags: ['epeiste', 'isekai', 'genie', 'protagoniste', 'calme'] },
  { id: 'asuna', name: 'Asuna', theme: 'anime', series: 'sword-art-online', tags: ['epeiste', 'isekai', 'determine', 'stratege', 'loyal'] },
  { id: 'sinon', name: 'Sinon', theme: 'anime', series: 'sword-art-online', tags: ['isekai', 'tireuse', 'calme', 'traumatise', 'determine'] },
  { id: 'klein', name: 'Klein', theme: 'anime', series: 'sword-art-online', tags: ['epeiste', 'isekai', 'loyal', 'comique', 'charismatique'] },
  { id: 'leafa', name: 'Leafa', theme: 'anime', series: 'sword-art-online', tags: ['epeiste', 'isekai', 'loyal', 'determine', 'attachant'] },
  { id: 'yuuki', name: 'Yuuki', theme: 'anime', series: 'sword-art-online', tags: ['epeiste', 'isekai', 'courageux', 'attachant', 'genie'] },
  { id: 'heathcliff', name: 'Heathcliff', theme: 'anime', series: 'sword-art-online', tags: ['epeiste', 'isekai', 'antagoniste', 'mysterieux', 'stratege'] },
  { id: 'silica', name: 'Silica', theme: 'anime', series: 'sword-art-online', tags: ['isekai', 'dresseur', 'timide', 'loyal', 'attachant'] },
  { id: 'lisbeth', name: 'Lisbeth', theme: 'anime', series: 'sword-art-online', tags: ['isekai', 'genie', 'loyal', 'sarcastique', 'determine'] },
  { id: 'alice-zuberg', name: 'Alice Zuberg', theme: 'anime', series: 'sword-art-online', tags: ['epeiste', 'isekai', 'determine', 'idealiste', 'courageux'] },
  // Tokyo Ghoul
  { id: 'kaneki', name: 'Ken Kaneki', theme: 'anime', series: 'tokyo-ghoul', tags: ['transformation', 'seinen', 'sombre', 'protagoniste', 'sacrifice'] },
  { id: 'touka', name: 'Touka Kirishima', theme: 'anime', series: 'tokyo-ghoul', tags: ['transformation', 'seinen', 'determine', 'loyal', 'combattant-corps-a-corps'] },
  { id: 'yomo', name: 'Renji Yomo', theme: 'anime', series: 'tokyo-ghoul', tags: ['transformation', 'seinen', 'calme', 'loyal', 'mysterieux'] },
  { id: 'nishiki', name: 'Nishiki Nishio', theme: 'anime', series: 'tokyo-ghoul', tags: ['transformation', 'seinen', 'sarcastique', 'rival', 'loyal'] },
  { id: 'juuzou', name: 'Juuzou Suzuya', theme: 'anime', series: 'tokyo-ghoul', tags: ['seinen', 'excentrique', 'traumatise', 'combattant-corps-a-corps', 'impulsif'] },
  { id: 'arima', name: 'Kishou Arima', theme: 'anime', series: 'tokyo-ghoul', tags: ['epeiste', 'seinen', 'calme', 'force-brute', 'mysterieux'] },
  { id: 'hide', name: 'Hideyoshi Nagachika', theme: 'anime', series: 'tokyo-ghoul', tags: ['seinen', 'loyal', 'comique', 'genie', 'sacrifice'] },
  { id: 'rize', name: 'Rize Kamishiro', theme: 'anime', series: 'tokyo-ghoul', tags: ['transformation', 'seinen', 'mysterieux', 'sombre', 'manipulateur'] },
  { id: 'uta', name: 'Uta', theme: 'anime', series: 'tokyo-ghoul', tags: ['transformation', 'seinen', 'excentrique', 'mysterieux', 'calme'] },
  { id: 'eto', name: 'Eto Yoshimura', theme: 'anime', series: 'tokyo-ghoul', tags: ['transformation', 'seinen', 'antagoniste', 'genie', 'manipulateur'] },
  // Cowboy Bebop
  { id: 'spike-spiegel', name: 'Spike Spiegel', theme: 'anime', series: 'cowboy-bebop', tags: ['chasseur-de-primes', 'seinen', 'sarcastique', 'passe-sombre', 'calme'] },
  { id: 'faye-valentine', name: 'Faye Valentine', theme: 'anime', series: 'cowboy-bebop', tags: ['chasseur-de-primes', 'seinen', 'sarcastique', 'independante', 'mysterieux'] },
  { id: 'jet-black', name: 'Jet Black', theme: 'anime', series: 'cowboy-bebop', tags: ['chasseur-de-primes', 'seinen', 'calme', 'mentor', 'passe-sombre'] },
  { id: 'edward-wong', name: 'Edward Wong (Ed)', theme: 'anime', series: 'cowboy-bebop', tags: ['chasseur-de-primes', 'seinen', 'excentrique', 'genie', 'comique'] },
  { id: 'ein', name: 'Ein', theme: 'anime', series: 'cowboy-bebop', tags: ['seinen', 'mysterieux', 'genie', 'attachant', 'mascotte'] },
  { id: 'vicious', name: 'Vicious', theme: 'anime', series: 'cowboy-bebop', tags: ['seinen', 'antagoniste', 'sombre', 'epeiste', 'vengeance'] },
  { id: 'julia', name: 'Julia', theme: 'anime', series: 'cowboy-bebop', tags: ['seinen', 'mysterieux', 'passe-sombre', 'calme', 'attachant'] },
  { id: 'punch', name: 'Punch', theme: 'anime', series: 'cowboy-bebop', tags: ['seinen', 'comique', 'excentrique', 'charismatique', 'orateur'] },
  { id: 'judy', name: 'Judy', theme: 'anime', series: 'cowboy-bebop', tags: ['seinen', 'comique', 'excentrique', 'charismatique', 'sarcastique'] },
  { id: 'gren', name: 'Gren', theme: 'anime', series: 'cowboy-bebop', tags: ['seinen', 'calme', 'passe-sombre', 'loyal', 'sacrifice'] },
  // Neon Genesis Evangelion
  { id: 'shinji', name: 'Shinji Ikari', theme: 'anime', series: 'evangelion', tags: ['pilote-robot', 'mecha', 'timide', 'protagoniste', 'traumatise'] },
  { id: 'rei-ayanami', name: 'Rei Ayanami', theme: 'anime', series: 'evangelion', tags: ['pilote-robot', 'mecha', 'calme', 'mysterieux', 'loyal'] },
  { id: 'asuka', name: 'Asuka Langley Soryu', theme: 'anime', series: 'evangelion', tags: ['pilote-robot', 'mecha', 'orgueilleux', 'traumatise', 'impulsif'] },
  { id: 'misato', name: 'Misato Katsuragi', theme: 'anime', series: 'evangelion', tags: ['mecha', 'stratege', 'mentor', 'passe-sombre', 'loyal'] },
  { id: 'gendo', name: 'Gendo Ikari', theme: 'anime', series: 'evangelion', tags: ['mecha', 'antagoniste', 'manipulateur', 'sombre', 'mysterieux'] },
  { id: 'ritsuko', name: 'Ritsuko Akagi', theme: 'anime', series: 'evangelion', tags: ['mecha', 'genie', 'calme', 'traumatise', 'mysterieux'] },
  { id: 'kaworu', name: 'Kaworu Nagisa', theme: 'anime', series: 'evangelion', tags: ['pilote-robot', 'mecha', 'mysterieux', 'calme', 'sacrifice'] },
  { id: 'toji', name: 'Toji Suzuhara', theme: 'anime', series: 'evangelion', tags: ['pilote-robot', 'mecha', 'loyal', 'hot-blooded', 'sacrifice'] },
  { id: 'kensuke', name: 'Kensuke Aida', theme: 'anime', series: 'evangelion', tags: ['mecha', 'comique', 'naif', 'loyal', 'excentrique'] },
  { id: 'kaji', name: 'Ryoji Kaji', theme: 'anime', series: 'evangelion', tags: ['mecha', 'agent-secret', 'charismatique', 'mysterieux', 'sacrifice'] },
  // Pokémon
  { id: 'ash-ketchum', name: 'Ash Ketchum', theme: 'anime', series: 'pokemon', tags: ['dresseur', 'enfance', 'determine', 'protagoniste', 'hot-blooded'] },
  { id: 'pikachu', name: 'Pikachu', theme: 'anime', series: 'pokemon', tags: ['enfance', 'loyal', 'mascotte', 'super-pouvoir', 'attachant'] },
  { id: 'misty', name: 'Misty', theme: 'anime', series: 'pokemon', tags: ['dresseur', 'enfance', 'hot-blooded', 'loyal', 'determine'] },
  { id: 'brock', name: 'Brock', theme: 'anime', series: 'pokemon', tags: ['dresseur', 'enfance', 'loyal', 'seducteur', 'comique'] },
  { id: 'jessie', name: 'Jessie', theme: 'anime', series: 'pokemon', tags: ['enfance', 'comique', 'ambitieux', 'loyal', 'excentrique'] },
  { id: 'james', name: 'James', theme: 'anime', series: 'pokemon', tags: ['enfance', 'comique', 'loyal', 'peureux', 'excentrique'] },
  { id: 'professor-oak', name: 'Professeur Chen', theme: 'anime', series: 'pokemon', tags: ['enfance', 'mentor', 'genie', 'calme', 'sage'] },
  { id: 'gary-oak', name: 'Gary Oak', theme: 'anime', series: 'pokemon', tags: ['dresseur', 'enfance', 'rival', 'orgueilleux', 'genie'] },
  { id: 'may', name: 'May', theme: 'anime', series: 'pokemon', tags: ['dresseur', 'enfance', 'determine', 'loyal', 'attachant'] },
  { id: 'dawn', name: 'Dawn', theme: 'anime', series: 'pokemon', tags: ['dresseur', 'enfance', 'determine', 'ambitieux', 'attachant'] },
  // Spy x Family
  { id: 'loid-forger', name: 'Loid Forger', theme: 'anime', series: 'spy-x-family', tags: ['agent-secret', 'seinen', 'stratege', 'calme', 'famille'] },
  { id: 'anya-forger', name: 'Anya Forger', theme: 'anime', series: 'spy-x-family', tags: ['enfance', 'seinen', 'comique', 'super-pouvoir', 'famille'] },
  { id: 'yor-forger', name: 'Yor Forger', theme: 'anime', series: 'spy-x-family', tags: ['assassin', 'seinen', 'famille', 'calme', 'force-brute'] },
  { id: 'bond-forger', name: 'Bond Forger', theme: 'anime', series: 'spy-x-family', tags: ['enfance', 'seinen', 'famille', 'loyal', 'mascotte'] },
  { id: 'damian', name: 'Damian Desmond', theme: 'anime', series: 'spy-x-family', tags: ['enfance', 'seinen', 'orgueilleux', 'rival', 'timide'] },
  { id: 'fiona', name: 'Fiona Frost', theme: 'anime', series: 'spy-x-family', tags: ['agent-secret', 'seinen', 'calme', 'stratege', 'rival'] },
  { id: 'franky-franklin', name: 'Franky Franklin', theme: 'anime', series: 'spy-x-family', tags: ['agent-secret', 'seinen', 'comique', 'loyal', 'genie'] },
  { id: 'yuri-briar', name: 'Yuri Briar', theme: 'anime', series: 'spy-x-family', tags: ['agent-secret', 'seinen', 'famille', 'impulsif', 'loyal'] },
  { id: 'sylvia', name: 'Sylvia Sherwood', theme: 'anime', series: 'spy-x-family', tags: ['agent-secret', 'seinen', 'stratege', 'calme', 'mysterieux'] },
  { id: 'becky', name: 'Becky Blackbell', theme: 'anime', series: 'spy-x-family', tags: ['enfance', 'seinen', 'loyal', 'comique', 'attachant'] },
  // Chainsaw Man
  { id: 'denji', name: 'Denji', theme: 'anime', series: 'chainsaw-man', tags: ['transformation', 'seinen', 'naif', 'protagoniste', 'impulsif'] },
  { id: 'power', name: 'Power', theme: 'anime', series: 'chainsaw-man', tags: ['transformation', 'seinen', 'comique', 'orgueilleux', 'loyal'] },
  { id: 'aki-hayakawa', name: 'Aki Hayakawa', theme: 'anime', series: 'chainsaw-man', tags: ['seinen', 'calme', 'vengeance', 'loyal', 'sacrifice'] },
  { id: 'makima', name: 'Makima', theme: 'anime', series: 'chainsaw-man', tags: ['seinen', 'antagoniste', 'manipulateur', 'calme', 'mysterieux'] },
  { id: 'kobeni', name: 'Kobeni Higashiyama', theme: 'anime', series: 'chainsaw-man', tags: ['seinen', 'peureux', 'comique', 'traumatise', 'loyal'] },
  { id: 'himeno', name: 'Himeno', theme: 'anime', series: 'chainsaw-man', tags: ['seinen', 'sarcastique', 'loyal', 'sacrifice', 'independante'] },
  { id: 'angel-devil', name: 'Angel Devil', theme: 'anime', series: 'chainsaw-man', tags: ['seinen', 'blase', 'mysterieux', 'loyal', 'naif'] },
  { id: 'reze', name: 'Reze', theme: 'anime', series: 'chainsaw-man', tags: ['seinen', 'manipulateur', 'mysterieux', 'force-brute', 'attachant'] },
  { id: 'quanxi', name: 'Quanxi', theme: 'anime', series: 'chainsaw-man', tags: ['seinen', 'force-brute', 'blase', 'independante', 'mysterieux'] },
  { id: 'kishibe', name: 'Kishibe', theme: 'anime', series: 'chainsaw-man', tags: ['seinen', 'mentor', 'force-brute', 'calme', 'excentrique'] },
  // Code Geass
  { id: 'lelouch', name: 'Lelouch Lamperouge', theme: 'anime', series: 'code-geass', tags: ['stratege', 'mecha', 'genie', 'antagoniste', 'masque'] },
  { id: 'suzaku', name: 'Suzaku Kururugi', theme: 'anime', series: 'code-geass', tags: ['pilote-robot', 'mecha', 'loyal', 'rival', 'idealiste'] },
  { id: 'cc', name: 'C.C.', theme: 'anime', series: 'code-geass', tags: ['mecha', 'mysterieux', 'immortel', 'sarcastique', 'calme'] },
  { id: 'kallen', name: 'Kallen Kozuki', theme: 'anime', series: 'code-geass', tags: ['pilote-robot', 'mecha', 'determine', 'loyal', 'hot-blooded'] },
  { id: 'nunnally', name: 'Nunnally Lamperouge', theme: 'anime', series: 'code-geass', tags: ['mecha', 'famille', 'idealiste', 'attachant', 'sacrifice'] },
  { id: 'todoh', name: 'Todoh Kyoshiro', theme: 'anime', series: 'code-geass', tags: ['pilote-robot', 'mecha', 'loyal', 'discipline', 'mentor'] },
  { id: 'jeremiah', name: 'Jeremiah Gottwald', theme: 'anime', series: 'code-geass', tags: ['pilote-robot', 'mecha', 'loyal', 'redemption', 'determine'] },
  { id: 'rolo', name: 'Rolo Lamperouge', theme: 'anime', series: 'code-geass', tags: ['mecha', 'assassin', 'famille', 'traumatise', 'loyal'] },
  { id: 'milly', name: 'Milly Ashford', theme: 'anime', series: 'code-geass', tags: ['mecha', 'comique', 'charismatique', 'excentrique', 'loyal'] },
  { id: 'schneizel', name: 'Schneizel el Britannia', theme: 'anime', series: 'code-geass', tags: ['mecha', 'stratege', 'genie', 'calme', 'ambitieux'] },

  // Films
  { id: 'luke-skywalker', name: 'Luke Skywalker', theme: 'films', tags: ['chevalier', 'science-fiction', 'heros', 'mentor-guide', 'epeiste'] },
  { id: 'dark-vador', name: 'Dark Vador', theme: 'films', tags: ['science-fiction', 'antagoniste', 'guerrier', 'masque', 'redemption'] },
  { id: 'iron-man', name: 'Tony Stark', theme: 'films', tags: ['super-heros', 'science-fiction', 'genie', 'riche', 'sarcastique'] },
  { id: 'batman', name: 'Bruce Wayne', theme: 'films', tags: ['super-heros', 'riche', 'vigilante', 'sombre', 'genie'] },
  { id: 'indiana-jones', name: 'Indiana Jones', theme: 'films', tags: ['aventurier', 'archeologue', 'action', 'charismatique', 'annees-30'] },
  { id: 'james-bond', name: 'James Bond', theme: 'films', tags: ['espion', 'action', 'charismatique', 'epoque-moderne', 'seducteur'] },
  { id: 'forrest-gump', name: 'Forrest Gump', theme: 'films', tags: ['drame', 'naif', 'heros-ordinaire', 'americana', 'attachant'] },
  { id: 'rocky', name: 'Rocky Balboa', theme: 'films', tags: ['drame', 'boxeur', 'heros-ordinaire', 'determine', 'americana'] },
  { id: 'gandalf', name: 'Gandalf', theme: 'films', tags: ['mage', 'fantasy', 'mentor', 'sage', 'epique'] },
  { id: 'dumbledore', name: 'Dumbledore', theme: 'films', tags: ['mage', 'fantasy', 'mentor', 'sage', 'mysterieux'] },
  { id: 'jack-sparrow', name: 'Jack Sparrow', theme: 'films', tags: ['pirate', 'aventurier', 'action', 'excentrique', 'charismatique'] },
  { id: 'katniss', name: 'Katniss Everdeen', theme: 'films', tags: ['heros-ordinaire', 'action', 'determine', 'dystopie', 'archere'] },
];
