/** Human-readable display names for the `series` slugs used by anime characters in data.ts. */
export const SERIES_LABELS: Record<string, string> = {
  'one-piece': 'One Piece',
  naruto: 'Naruto',
  'dragon-ball': 'Dragon Ball',
  'death-note': 'Death Note',
  'attack-on-titan': "L'Attaque des Titans",
  'fullmetal-alchemist': 'Fullmetal Alchemist',
  'my-hero-academia': 'My Hero Academia',
  'demon-slayer': 'Demon Slayer',
  'jujutsu-kaisen': 'Jujutsu Kaisen',
  bleach: 'Bleach',
  'hunter-x-hunter': 'Hunter x Hunter',
  'one-punch-man': 'One Punch Man',
  'sword-art-online': 'Sword Art Online',
  'tokyo-ghoul': 'Tokyo Ghoul',
  'cowboy-bebop': 'Cowboy Bebop',
  evangelion: 'Neon Genesis Evangelion',
  pokemon: 'Pokémon',
  'spy-x-family': 'Spy x Family',
  'chainsaw-man': 'Chainsaw Man',
  'code-geass': 'Code Geass',

  // Histoire sub-categories (era/domain buckets).
  guerre: 'Guerre',
  'egypte-antique': 'Égypte antique',
  'grece-antique': 'Grèce antique',
  'rome-antique': 'Rome antique',
  'moyen-age': 'Moyen Âge',
  renaissance: 'Renaissance',
  exploration: 'Exploration',
  science: 'Science',
  'philosophie-religion': 'Philosophie & religion',
  monarchie: 'Monarchie',
  revolution: 'Révolutions',
  'art-culture': 'Art & culture',
  'droits-civiques': 'Droits civiques',
  invention: 'Invention & technologie',
  'guerre-mondiale': 'Guerres mondiales',
  'politique-moderne': 'Politique moderne',

  // Films sub-categories (source film/franchise).
  'star-wars': 'Star Wars',
  marvel: 'Marvel',
  dc: 'DC',
  'seigneur-des-anneaux': 'Le Seigneur des anneaux',
  'harry-potter': 'Harry Potter',
  matrix: 'Matrix',
  titanic: 'Titanic',
  'die-hard': 'Die Hard',
  terminator: 'Terminator',
  alien: 'Alien',
  gladiator: 'Gladiator',
  godfather: 'Le Parrain',
  scarface: 'Scarface',
  'back-to-the-future': 'Retour vers le futur',
  'blade-runner': 'Blade Runner',
  'the-shining': 'Shining',
  psycho: 'Psychose',
  'gone-with-the-wind': 'Autant en emporte le vent',
  'to-kill-a-mockingbird': 'Du silence et des ombres',
  'mary-poppins': 'Mary Poppins',
  'wizard-of-oz': 'Le Magicien d’Oz',
  'king-kong': 'King Kong',
  godzilla: 'Godzilla',
  'edward-scissorhands': 'Edward aux mains d’argent',
  'nightmare-before-christmas': "L'Étrange Noël de M. Jack",
  beetlejuice: 'Beetlejuice',
  rocky: 'Rocky',
  'forrest-gump': 'Forrest Gump',
  'indiana-jones': 'Indiana Jones',
  'james-bond': 'James Bond',
  'pirates-des-caraibes': 'Pirates des Caraïbes',
  'hunger-games': 'Hunger Games',
  et: 'E.T.',
  'fight-club': 'Fight Club',
  'willy-wonka': 'Charlie et la chocolaterie',
  'nightmare-on-elm-street': "Les Griffes de la nuit",
  halloween: 'Halloween',
  dracula: 'Dracula',
  frankenstein: 'Frankenstein',
  'silence-of-the-lambs': 'Le Silence des agneaux',
  braveheart: 'Braveheart',
  'jason-bourne': 'Jason Bourne',
  'john-wick': 'John Wick',
  'mission-impossible': 'Mission: Impossible',
  '2001-space-odyssey': "2001, l'Odyssée de l'espace",
  'ferris-bueller': 'La Folle Journée de Ferris Bueller',
  'taxi-driver': 'Taxi Driver',
  'mrs-doubtfire': 'Madame Doubtfire',
  'austin-powers': 'Austin Powers',
  'pink-panther': 'La Panthère rose',
  shrek: 'Shrek',
  'toy-story': 'Toy Story',
  'roi-lion': 'Le Roi Lion',
  'reine-des-neiges': 'La Reine des neiges',
  'nemo': 'Le Monde de Nemo',
  ratatouille: 'Ratatouille',
  'wall-e': 'WALL-E',
  'monstres-et-cie': 'Monstres & Cie',
};
